// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.hi');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "टिप्पणी छोड़ें";
Blockly.Msg.AUTH = "Please authorize this app to enable your work to be saved and to allow it to be shared by you.";  // untranslated
Blockly.Msg.CHANGE_VALUE_TITLE = "मान परिवर्तित करें:";
Blockly.Msg.CHAT = "Chat with your collaborator by typing in this box!";  // untranslated
Blockly.Msg.COLLAPSE_ALL = "ब्लॉक संक्षिप्त करें";
Blockly.Msg.COLLAPSE_BLOCK = "ब्लॉक को संक्षिप्त करें";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "रंग 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "रंग 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "अनुपात";
Blockly.Msg.COLOUR_BLEND_TITLE = "मिश्रण करें";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "दिए गए अनुपात (0.0 - 1.0) के साथ दो रंगों का मिश्रण करता है।";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://en.wikipedia.org/wiki/Color";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "पैलेट से एक रंग चुनें।";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "रैन्डम रंग";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "रैन्डम्ली एक रंग चयन करें।";
Blockly.Msg.COLOUR_RGB_BLUE = "नीला";
Blockly.Msg.COLOUR_RGB_GREEN = "हरा";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "लाल";
Blockly.Msg.COLOUR_RGB_TITLE = "इसके साथ रंग करें";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Create a colour with the specified amount of red, green, and blue.  All values must be between 0 and 100.";  // untranslated
Blockly.Msg.COMMENT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.COMMENT_TITLE = "Program Comment";  // untranslated
Blockly.Msg.COMMENT_TOOLTIP = "Comment Text";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://code.google.com/p/blockly/wiki/Loops#Loop_Termination_Blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "लूप से बाहर निकलें";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "लूप का अगला आईटरेशन जारी रखें";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "भीतरी लूप से बाहर निकलें।";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "बाकी बचे लूप को छोड़ें, और अगला आईटरेशन जारी रखें।";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "सावधान: ये ब्लॉक केवल लूप के अंदर इस्तेमाल किया जा सकता है।";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST = "सूची में";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST_TAIL = "";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_INPUT_ITEM = "प्रत्येक आइटम के लिए";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "For each item in a list, set the variable '%1' to the item, and then do some statements.";  // untranslated
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY = "from %1 to %2 by %3";  // untranslated
Blockly.Msg.CONTROLS_FOR_INPUT_WITH = "काउंट करें";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Have the variable %1 take on the values from the start number to the end number, counting by the specified interval, and do the specified blocks.";  // untranslated
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "यदि ब्लॉक मे एक शर्त जोड़ें।";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Add a final, catch-all condition to the if block.";  // untranslated
Blockly.Msg.CONTROLS_IF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Add, remove, or reorder sections to reconfigure this if block.";  // untranslated
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "एल्स";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "एल्स इफ";
Blockly.Msg.CONTROLS_IF_MSG_IF = "इफ";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "यदी मान ट्रू है, तो कुछ स्टेट्मेंट्स चलाएँ।";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "If a value is true, then do the first block of statements.  Otherwise, do the second block of statements.";  // untranslated
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "If the first value is true, then do the first block of statements.  Otherwise, if the second value is true, do the second block of statements.";  // untranslated
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "If the first value is true, then do the first block of statements.  Otherwise, if the second value is true, do the second block of statements.  If none of the values are true, do the last block of statements.";  // untranslated
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "डू";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "%1 बार दोहराएँ";
Blockly.Msg.CONTROLS_REPEAT_TITLE_REPEAT = "दोहराएँ";
Blockly.Msg.CONTROLS_REPEAT_TITLE_TIMES = "इतनी बार";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "कुछ स्टेट्मन्ट कई बार चलाएँ।";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "दोहराएँ जब तक";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "दोहराएँ जब कि";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "जब तक मान फॉल्स है, तब तक कुछ स्टेट्मेंट्स चलाएँ।";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "जब तक मान ट्रू है, तब तक कुछ स्टेट्मेंट्स चलाएँ।";
Blockly.Msg.DELETE_BLOCK = "ब्लॉक हटाएँ";
Blockly.Msg.DELETE_X_BLOCKS = "%1 ब्लॉक हटाएँ";
Blockly.Msg.DISABLE_BLOCK = "ब्लॉक को अक्षम करें";
Blockly.Msg.DUPLICATE_BLOCK = "कॉपी करें";
Blockly.Msg.ENABLE_BLOCK = "ब्लॉक को सक्षम करें";
Blockly.Msg.EXPAND_ALL = "ब्लॉक विस्तार करें";
Blockly.Msg.EXPAND_BLOCK = "ब्लॉक का विस्तार करें";
Blockly.Msg.EXPANSION_ELEVATION_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_ELEVATION_TOOLTI = "Gripper Servo Elevation";  // untranslated
Blockly.Msg.EXPANSION_EXP1OFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1OFF_TOOLTIP = "Turn Expansion 1 +3.3V Power Off";  // untranslated
Blockly.Msg.EXPANSION_EXP1ON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1ON_TOOLTIP = "Turn Expansion 1 +3.3V Power On";  // untranslated
Blockly.Msg.EXPANSION_EXP1_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1_OFF = "expansion 1 power off";  // untranslated
Blockly.Msg.EXPANSION_EXP1_ON = "expansion 1 power on";  // untranslated
Blockly.Msg.EXPANSION_EXP1_TOOLTIP = "Expansion 1 Power Control";  // untranslated
Blockly.Msg.EXPANSION_EXP2OFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2OFF_TOOLTIP = "Turn Expansion 2 +3.3V Power Off";  // untranslated
Blockly.Msg.EXPANSION_EXP2ON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2ON_TOOLTIP = "Turn Expansion 2 +3.3V Power On";  // untranslated
Blockly.Msg.EXPANSION_EXP2_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2_OFF = "expansion 2 power off";  // untranslated
Blockly.Msg.EXPANSION_EXP2_ON = "expansion 2 power on";  // untranslated
Blockly.Msg.EXPANSION_EXP2_TOOLTIP = "Expansion 2 Power Control";  // untranslated
Blockly.Msg.EXPANSION_GRIPPER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_GRIPPER_TOOLTIP = "Gripper Servo Open/Close";  // untranslated
Blockly.Msg.EXPANSION_SERVOOFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVOOFF_TOOLTIP = "Turn Servo +5V Power Off";  // untranslated
Blockly.Msg.EXPANSION_SERVOON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVOON_TOOLTIP = "Turn Servo +5V Power On";  // untranslated
Blockly.Msg.EXPANSION_SERVO_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVO_OFF = "servo power off";  // untranslated
Blockly.Msg.EXPANSION_SERVO_ON = "servo power on";  // untranslated
Blockly.Msg.EXPANSION_SERVO_TOOLTIP = "Servo Power Control";  // untranslated
Blockly.Msg.EXTERNAL_INPUTS = "बाहरी इनपुट";
Blockly.Msg.HELP = "सहायता";
Blockly.Msg.INLINE_INPUTS = "इनलाइन इनपुट";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://en.wikipedia.org/wiki/Linked_list#Empty_lists";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "खाली सूची बनाएँ";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Returns a list, of length 0, containing no data records";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "सूची";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Add, remove, or reorder sections to reconfigure this list block.";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "इसके सूची बनाएँ";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "सूची मे एक आइटम जोड़ें।";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "कितने भी आइटम वाली एक सूची बनाएँ।";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "पहला";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "अंत से #";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET = "get";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "get and remove";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_LAST = "आखिरी";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "रैन्डम";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "निकालें";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "सूची का पहला आइटम रिटर्न करता है।";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Returns the item at the specified position in a list.  #1 is the last item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Returns the item at the specified position in a list.  #1 is the first item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "सूची का आखरी आइटम रिटर्न करता है।";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "सूची से रैन्डम आइटम रिटर्न करता है।";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "सूची का पहला आइटम निकालता है और रिटर्न करता है।";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Removes and returns the item at the specified position in a list.  #1 is the last item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Removes and returns the item at the specified position in a list.  #1 is the first item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "सूची का आखरी आइटम निकालता है और रिटर्न करता है।";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "सूची से रैन्डम आइटम निकालता है और रिटर्न करता है।";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "सूची का पहला आइटम निकालता है।";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Removes the item at the specified position in a list.  #1 is the last item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Removes the item at the specified position in a list.  #1 is the first item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "सूची का आखरी आइटम निकालता है।";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "सूची से रैन्डम आइटम निकालता है।";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "to # from end";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "to #";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "to last";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#Getting_a_sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "get sub-list from first";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "get sub-list from # from end";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "get sub-list from #";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "सूची के बताए गये भाग की कॉपी बनता है।";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "आइटम पहली बार जहाँ आया है उसे ढूढ़े";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#Getting_Items_from_a_List";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "आइटम आखरी बार जहाँ आया है उसे ढूढ़े";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Returns the index of the first/last occurrence of the item in the list.  Returns 0 if text is not found.";  // untranslated
Blockly.Msg.LISTS_INLIST = "सूची में";
Blockly.Msg.LISTS_IS_EMPTY_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#is_empty";  // untranslated
Blockly.Msg.LISTS_IS_EMPTY_TITLE = "%1 खाली है";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#length_of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "%1 की लंबाई";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "सूची की लंबाई रिटर्न करता है।";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#create_list_with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "create list with item %1 repeated %2 times";  // untranslated
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Creates a list consisting of the given value repeated the specified number of times.";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#in_list_..._set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "as";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INSERT = "insert at";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_SET = "सैट करें";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "आइटम को सूची के शुरू में इनसर्ट करता है।";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "सूची मे बताए गये स्थान में आइटम इनसर्ट करता है। #1 आखरी आइटम है।";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "सूची मे बताए गये स्थान में आइटम इनसर्ट करता है। #1 पहला आइटम है।";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "आइटम को सूची के अंत में जोड़ता है।";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "आइटम को सूची में रैन्डम्ली इनसर्ट करता है।";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "सूची में पहला आइटम सैट करता है।";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "सूची मे बताए गये स्थान में आइटम सैट करता है। #1 आखरी आइटम है।";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "सूची मे बताए गये स्थान में आइटम सैट करता है। #1 पहला आइटम है।";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "सूची में आखरी आइटम सैट करता है।";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "सूची में रैन्डम आइटम सैट करता है।";
Blockly.Msg.LISTS_TOOLTIP = "यदि सूची खाली है तो ट्रू रिटर्न करता है।";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "फॉल्स";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "ट्रू या फॉल्स रिटर्न करता है।";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "ट्रू";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "ट्रू रिटर्न करें यदि दोनो इनपुट इक दूसरे के बराबर हों।";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "ट्रू रिटर्न करें यदि पहला इनपुट दूसरे इनपुट से बड़ा हो।";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "ट्रू रिटर्न करें यदि पहला इनपुट दूसरे इनपुट से बड़ा हो या बराबर हो।";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "ट्रू रिटर्न करें यदि पहला इनपुट दूसरे इनपुट से छोटा हो।";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "ट्रू रिटर्न करें यदि पहला इनपुट दूसरे इनपुट से छोटा हो या बराबर हो।";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "ट्रू रिटर्न करें यदि दोनो इनपुट इक दूसरे के बराबर नहीं हों।";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "NOT (पूरक) %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "ट्रू रिटर्न करता है यदि इनपुट फॉल्स है। फॉल्स रिटर्न करता है यदि इनपुट ट्रू है।";
Blockly.Msg.LOGIC_NULL = "NULL (अमान्य)";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "null (अमान्य) रिटर्न करता है।";
Blockly.Msg.LOGIC_OPERATION_AND = "AND (तथा)";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "OR (अथवा)";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "ट्रू रिटर्न करें यदि दोनो इनपुट ट्रू हों।";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "ट्रू रिटर्न करें यदि दोनो मे से इक इनपुट ट्रू हो।";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "टेस्ट";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "यदि फॉल्स है";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "यदि ट्रू है";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Check the condition in 'test'. If the condition is true, returns the 'if true' value; otherwise returns the 'if false' value.";  // untranslated
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://en.wikipedia.org/wiki/Arithmetic";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "दो संख्याओं का योग रिटर्न करें।";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "दो संख्याओं का भागफल रिटर्न करें।";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "दो संख्याओं का अंतर रिटर्न करें।";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MODULO = "Return the remainder of the division operation.";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "दो संख्याओं का गुणन रिटर्न करें।";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Return the first number raised to the power of the second number.";  // untranslated
Blockly.Msg.MATH_BITWISE_AND = "&";  // untranslated
Blockly.Msg.MATH_BITWISE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_BITWISE_OR = "|";  // untranslated
Blockly.Msg.MATH_BITWISE_TOOLTIP = "Bitwise Operations";  // untranslated
Blockly.Msg.MATH_BITWISE_XOR = "^";  // untranslated
Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg.MATH_CHANGE_INPUT_BY = "by";  // untranslated
Blockly.Msg.MATH_CHANGE_TITLE_CHANGE = "बदलें";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "संख्या को चर '%1' से जोड़ें।";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Return one of the common constants: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (infinity).";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "constrain %1 low %2 high %3";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Constrain a number to be between the specified limits (inclusive).";  // untranslated
Blockly.Msg.MATH_DIVISION_SYMBOL = "/";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "इसके द्वारा विभाज्य है";
Blockly.Msg.MATH_IS_EVEN = "सम है";
Blockly.Msg.MATH_IS_NEGATIVE = "ऋणात्मक है";
Blockly.Msg.MATH_IS_ODD = "विषम है";
Blockly.Msg.MATH_IS_POSITIVE = "धनात्मक है";
Blockly.Msg.MATH_IS_PRIME = "अभाज्य है";
Blockly.Msg.MATH_IS_TOOLTIP = "Check if a number is an even, odd, prime, whole, positive, negative, or if it is divisible by certain number.  Returns true or false.";  // untranslated
Blockly.Msg.MATH_IS_WHOLE = "पूर्णांक है";
Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg.MATH_MODULO_SYMBOL = "%";  // untranslated
Blockly.Msg.MATH_MODULO_TITLE = "%1 ÷ %2 का शेषफल";
Blockly.Msg.MATH_MODULO_TOOLTIP = "दो संख्याओं के भाग का शेषफल रिटर्न करें।";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "*";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://en.wikipedia.org/wiki/Number";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "एक संख्या।";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "सूची का औसत मान";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "सूची मे अधिकतम";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "सूची की माध्यिका";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "सूची मे न्यूनतम";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "सूची का मोड";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "सूची का रैन्डम आइटम";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "सूची का मानक विचलन";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "सूची का योग";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Return the average (arithmetic mean) of the numeric values in the list.";  // untranslated
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "सूची मे सबसे बड़ी संख्या रिटर्न करें।";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "सूची की माध्यिका संख्या रिटर्न करें।";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "सूची मे सबसे छोटी संख्या रिटर्न करें।";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "सूची मे सबसे आम आइटम(s) की सूची रिटर्न करें।";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "सूची से एक रैन्डम आइटम रिटर्न करें।";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "सूची का मानक विचलन रिटर्न करें।";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "सूची की सभी संख्याओं का योग रिटर्न करें।";
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "रैन्डम अंश";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Return a random fraction between 0.0 (inclusive) and 1.0 (exclusive).";  // untranslated
Blockly.Msg.MATH_RANDOM_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "%1 से % 2 तक रैन्डम पूर्णांक";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Return a random integer between the two specified limits, inclusive.";  // untranslated
Blockly.Msg.MATH_RANDOM_TITLE = "Random Number (0-99)";  // untranslated
Blockly.Msg.MATH_RANDOM_TOOLTIP = "Return Random Number";  // untranslated
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "पूर्णांक बनाएँ";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "घटा के पूर्णांक बनाएँ";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "बड़ा के पूर्णांक बनाएँ";
Blockly.Msg.MATH_ROUND_TOOLTIP = "संख्या को बड़ा या घटा के पूर्णांक बनाएँ।";
Blockly.Msg.MATH_SHIFT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_SHIFT_LEFT = "<<";  // untranslated
Blockly.Msg.MATH_SHIFT_RIGHT = ">>";  // untranslated
Blockly.Msg.MATH_SHIFT_TOOLTIP = "Bit Shift Operations";  // untranslated
Blockly.Msg.MATH_SINGLE_HELPURL = "https://en.wikipedia.org/wiki/Square_root";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "परम";
Blockly.Msg.MATH_SINGLE_OP_NEGATION = "negate";  // untranslated
Blockly.Msg.MATH_SINGLE_OP_ROOT = "वर्गमूल";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "संख्या का परम मान रिटर्न करें।";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Return e to the power of a number.";  // untranslated
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "संख्या का प्राकृतिक लघुगणक रिटर्न करें।";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "संख्या का मूल 10 लघुगणक रिटर्न करें।";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "संख्या का निषेध मान रिटर्न करें।";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Return 10 to the power of a number.";  // untranslated
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "संख्या का वर्गमूल रिटर्न करें।";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "संख्या का आर्ककोसाइन रिटर्न करें।";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "संख्या का आर्कसाइन रिटर्न करें।";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "संख्या का आर्कटैन्जन्ट रिटर्न करें।";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "डिग्री का कोसाइन रिटर्न करें (रेडियन नही)";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "डिग्री का साइन रिटर्न करें (रेडियन नही)";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "डिग्री का टैन्जन्ट रिटर्न करें (रेडियन नही)";
Blockly.Msg.ME = "Me";  // untranslated
Blockly.Msg.MULTIMEDIA_DISPLAYBMP_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_DISPLAYBMP_TOOLTIP = "Display BMP File on OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_DOUPDATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_DOUPDATE_TOOLTIP = "Do an Update to the OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_HIGH = "volume high";  // untranslated
Blockly.Msg.MULTIMEDIA_LOW = "volume low";  // untranslated
Blockly.Msg.MULTIMEDIA_MEDIUM = "volume medium";  // untranslated
Blockly.Msg.MULTIMEDIA_MUTE = "volume mute";  // untranslated
Blockly.Msg.MULTIMEDIA_PLAYWAV_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_PLAYWAV_TOOLTIP = "Play WAV File on Jade Robot";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_TITLE = "playing active";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_TOOLTIP = "Return Not Zero if WAV File still playing";  // untranslated
Blockly.Msg.MULTIMEDIA_STOPUPDATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_STOPUPDATE_TOOLTIP = "Stop Updating the OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_VOLUME_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_VOLUME_TOOLTIP = "Set Speaker Volume";  // untranslated
Blockly.Msg.NEW_VARIABLE = "नया चर...";
Blockly.Msg.NEW_VARIABLE_TITLE = "नए चर का नाम:";
Blockly.Msg.OLED_COLOR_BLACK = "color black";  // untranslated
Blockly.Msg.OLED_COLOR_GREEN = "color green";  // untranslated
Blockly.Msg.OLED_COLOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.OLED_COLOR_TOOLTIP = "Set OLED Draw Color";  // untranslated
Blockly.Msg.OLED_DRAW_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.OLED_DRAW_LINE = "draw line";  // untranslated
Blockly.Msg.OLED_DRAW_RECT = "draw rectangle";  // untranslated
Blockly.Msg.OLED_DRAW_TOOLTIP = "Draw from Cursor to End";  // untranslated
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "allow statements";  // untranslated
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = ": के साथ";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "";  // untranslated
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "यूज़र द्वारा वर्णन किया गया फ़ंक्शन '%1' चलाएँ।";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "यूज़र द्वारा वर्णन किया गया फ़ंक्शन '%1' चलाएँ और उसका आउटपुट इस्तेमाल करें।";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = ": के साथ";
Blockly.Msg.PROCEDURES_CREATE_DO = "'%1' बनाएँ";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "कुछ करें";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "बिना आउटपुट वाला एक फ़ंक्शन बनाता है।";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = "functionName";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "रिटर्न";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "आउटपुट वाला एक फ़ंक्शन बनाता है।";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "सावधान: इस फ़ंक्शन मे डुप्लिकेट पैरामीटर हैं।";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "फ़ंक्शन परिभाषा को हाइलाइट करें";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "यदि एक मान ट्रू है तो, दूसरा मान रिटर्न करें।";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "सावधान: ये ब्लॉक फ़ंक्शन परिभाषा के अंदर ही इस्तेमाल किया जा सकता।";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "इनपुट का नाम:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Add an input to the function.";  // untranslated
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "इनपुट";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Add, remove, or reorder inputs to this function.";  // untranslated
Blockly.Msg.REMOVE_COMMENT = "टिप्पणी हटायें";
Blockly.Msg.RENAME_VARIABLE = "चर का नाम बदलें...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "सभी '%1' चरों के नाम बदलें:";
Blockly.Msg.ROBOT_LED_FLASH = "led flash";  // untranslated
Blockly.Msg.ROBOT_LED_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.ROBOT_LED_OFF = "led off";  // untranslated
Blockly.Msg.ROBOT_LED_ON = "led on";  // untranslated
Blockly.Msg.ROBOT_LED_TOOLTIP = "Set LED";  // untranslated
Blockly.Msg.SENSOR_BATTERY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_BATTERY_TITLE = "battery level";  // untranslated
Blockly.Msg.SENSOR_BATTERY_TOOLTIP = "Return Battery Level";  // untranslated
Blockly.Msg.SENSOR_BUTTON_DOWN = "button down pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_ENTER = "button enter pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_BUTTON_LEFT = "button left pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_RIGHT = "button right pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_TOOLTIP = "Return Button State";  // untranslated
Blockly.Msg.SENSOR_BUTTON_UP = "button up pressed";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_LEFT = "light left";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_REAR = "light rear";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_RIGHT = "light right";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_TOOLTIP = "Returns Light Sensor.";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_LEFT = "line left";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_MIDDLE = "line middle";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_RIGHT = "line right";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_TOOLTIP = "Returns Line Sensor.";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_LEFTFRONT = "object left front";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_LEFTSIDE = "object left side";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_REAR = "object rear";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_RIGHTFRONT = "object right front";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_RIGHTSIDE = "object right side";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_TOOLTIP = "Returns Object Sensor.";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_BLUE = "spectrometer blue";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_GREEN = "spectrometer green";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_IR880 = "spectrometer 880nm";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_IR940 = "spectrometer 940nm";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_RED = "spectrometer red";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_TOOLTIP = "Return Spectrometer Reading";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_YELLOW = "spectrometer yellow";  // untranslated
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "से जोड़ें ये टेक्स्ट";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "इस";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "कुछ टेक्स्ट इस चर '%1' से जोड़ें।";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Adjusting_text_case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "छोटे अक्षर मे";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "टाइटल केस मे";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "बड़े अक्षर मे";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "टेक्स्ट की कॉपी भिन्न केस (अक्षर से संबंधित) मे रिटर्न करें।";
Blockly.Msg.TEXT_CHARAT_FIRST = "पहला अक्षर पाएँ";
Blockly.Msg.TEXT_CHARAT_FROM_END = "आखिर से अक्षर # पाएँ";
Blockly.Msg.TEXT_CHARAT_FROM_START = "अक्षर # पाएँ";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Extracting_text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "इस टेक्स्ट मे";
Blockly.Msg.TEXT_CHARAT_LAST = "आखरी अक्षर पाएँ";
Blockly.Msg.TEXT_CHARAT_RANDOM = "रैन्डम अक्षर पाएँ";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "बताई गयी जगह से अक्षर रिटर्न करता है";
Blockly.Msg.TEXT_CLEARDISPLAY_TOOLTIP = "Clear OLED Display";  // untranslated
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "सूची मे एक आइटम जोड़ें।";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "जोड़";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Add, remove, or reorder sections to reconfigure this text block.";  // untranslated
Blockly.Msg.TEXT_DRAWNUMBER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_DRAWNUMBER_TOOLTIP = "Draw the specified number";  // untranslated
Blockly.Msg.TEXT_DRAWTEXT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_DRAWTEXT_TOOLTIP = "Draw the specified text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "आखिर से यहाँ तक अक्षर #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "यहाँ तक अक्षर #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "यहाँ तक आखरी अक्षर";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Extracting_a_region_of_text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "इस टेक्स्ट मे";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "पहले अक्षर से सबस्ट्रिंग पाएँ";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "आखरी अक्षर # से सबस्ट्रिंग पाएँ";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "अक्षर # से सबस्ट्रिंग पाएँ";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "टेक्स्ट का बताया गया अंश रिटर्न करता है";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Finding_text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "इस टेक्स्ट मे";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "टेक्स्ट पहली बार जहाँ आया है उसे ढूढ़े";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "टेक्स्ट आखरी बार जहाँ आया है उसे ढूढ़े";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Returns the index of the first/last occurrence of first text in the second text.  Returns 0 if text is not found.";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Checking_for_empty_text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 खाली है";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "ट्रू रिटर्न करता है यदि दिया गया टेक्स्ट खाली है।";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "इसके साथ टेक्स्ट बनाएँ";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Create a piece of text by joining together any number of items.";  // untranslated
Blockly.Msg.TEXT_LEFTMOTOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_LEFTMOTOR_TITLE = "Set Left Motor %1";  // untranslated
Blockly.Msg.TEXT_LEFTMOTOR_TOOLTIP = "Specify the Value for the Left Motor.";  // untranslated
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "%1 की लंबाई";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "दिए गये टेक्स्ट मे अक्षरों की संख्या रिटर्न करता है (खाली स्थान मिला के)।";
Blockly.Msg.TEXT_MOTORSFORWARD_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSFORWARD_TITLE = "Move Robot Forward";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_TITLE = "Turn Left";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_TOOLTIP = "Turn Robot Left";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_TITLE = "Robot Reverse";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_TOOLTIP = "Move Robot Backward";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_TITLE = "Turn Right";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_TOOLTIP = "Turn Robot Right";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_TITLE = "Stop Robot";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_TOOLTIP = "Stop Robot";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_TITLE = "Robot Stutter";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_TOOLTIP = "Robot Stutter";  // untranslated
Blockly.Msg.TEXT_OLEDCLEARDISPLAY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDCURSOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDCURSOR_TOOLTIP = "Set the Draw Position";  // untranslated
Blockly.Msg.TEXT_OLEDEND_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDEND_TOOLTIP = "Set the End Draw Position";  // untranslated
Blockly.Msg.TEXT_PRINT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "प्रिंट करें %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "दिया गया टेक्स्ट प्रिंट करें, संख्या या अन्य मान।";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Getting_input_from_the_user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "यूज़र से संख्या के लिए प्रॉम्प्ट करें।";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "यूज़र से कुछ टेक्स्ट के लिए प्रॉम्प्ट करें।";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "सूचना के साथ संख्या के लिए प्रॉम्प्ट करें";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "सूचना के साथ टेक्स्ट के लिए प्रॉम्प्ट करें";
Blockly.Msg.TEXT_RIGHTMOTOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_RIGHTMOTOR_TOOLTIP = "Specify the Value for the Right Motor.";  // untranslated
Blockly.Msg.TEXT_ROBOTDELAY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_ROBOTDELAY_TITLE = "Delay in ms %1";  // untranslated
Blockly.Msg.TEXT_SETMOTORS_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_SETMOTORS_TOOLTIP = "Specify the Value for the Motors.";  // untranslated
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "एक अक्षर, शब्द, या टेक्स्ट की पंक्ति।";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Trimming_%28removing%29_spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "रिक्त स्थान को इस टेक्स्ट के दोनों तरफ से निकालें";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "रिक्त स्थान को इस टेक्स्ट के बायें तरफ से निकालें";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "रिक्त स्थान को इस टेक्स्ट के दाईं तरफ से निकालें";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Return a copy of the text with spaces removed from one or both ends.";  // untranslated
Blockly.Msg.VARIABLES_DEFAULT_NAME = "आइटम";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "सेट '%1' बनाएँ";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.VARIABLES_GET_TAIL = "";  // untranslated
Blockly.Msg.VARIABLES_GET_TITLE = "";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "इस चर का मान रिटर्न करता है।";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Create 'get %1'";  // untranslated
Blockly.Msg.VARIABLES_SET_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.VARIABLES_SET_TAIL = "को";
Blockly.Msg.VARIABLES_SET_TITLE = "सेट करें";
Blockly.Msg.VARIABLES_SET_TOOLTIP = "इस चर को इनपुट के बराबर सेट करता है।";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE;
Blockly.Msg.VARIABLES_SET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;