// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.it');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "Aggiungi commento";
Blockly.Msg.AUTH = "Autorizza questa applicazione per consentire di salvare il tuo lavoro e per essere condiviso.";
Blockly.Msg.CHANGE_VALUE_TITLE = "Modifica valore:";
Blockly.Msg.CHAT = "Chatta con il tuo collaboratore scrivendo in questo box!";
Blockly.Msg.COLLAPSE_ALL = "Comprimi blocchi";
Blockly.Msg.COLLAPSE_BLOCK = "Comprimi blocco";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "colore 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "colore 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "rapporto";
Blockly.Msg.COLOUR_BLEND_TITLE = "miscela";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Mescola due colori insieme con un determinato rapporto (0.0 - 1.0).";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://it.wikipedia.org/wiki/Colore";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Scegli un colore dalla tavolozza.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "colore casuale";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Scegli un colore a caso.";
Blockly.Msg.COLOUR_RGB_BLUE = "blu";
Blockly.Msg.COLOUR_RGB_GREEN = "verde";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "rosso";
Blockly.Msg.COLOUR_RGB_TITLE = "colora con";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Crea un colore con la quantità specificata di rosso, verde e blu. Tutti i valori devono essere compresi tra 0 e 100.";
Blockly.Msg.COMMENT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.COMMENT_TITLE = "Program Comment";  // untranslated
Blockly.Msg.COMMENT_TOOLTIP = "Comment Text";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://code.google.com/p/blockly/wiki/Loops#Loop_Termination_Blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "esce dal ciclo";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "prosegui con la successiva iterazione del ciclo";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Esce dal ciclo.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Salta il resto di questo ciclo e prosegue con la successiva iterazione.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Attenzioneː Questo blocco può essere usato solo in un ciclo.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST = "nella lista";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST_TAIL = "";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_INPUT_ITEM = "per ogni elemento";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Per ogni elemento in una lista, imposta la variabile '%1'  pari all'elemento e quindi esegue alcune istruzioni.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY = "da %1 a %2 per %3";
Blockly.Msg.CONTROLS_FOR_INPUT_WITH = "conta con";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Fa sì che la variabile %1 prenda tutti i valori a partire dal numero di partenza fino a quello di arrivo, con passo pari all'intervallo specificato, ed esegue il blocco indicato.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Aggiungi una condizione al blocco se.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Aggiungi una condizione finale pigliatutto al blocco se.";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Aggiungi, elimina o riordina le sezioni per riconfigurare questo blocco se.";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "altrimenti";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "altrimenti se";
Blockly.Msg.CONTROLS_IF_MSG_IF = "se";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "Se un valore è vero allora esegue alcune istruzioni.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Se un valore è vero allora esegue il primo blocco di istruzioni. Altrimenti esegue il secondo blocco di istruzioni.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Se il primo valore è vero allora esegue un primo blocco di istruzioni. Altrimenti, se il secondo valore è vero, esegue un secondo blocco di istruzioni.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Se il primo valore è vero allora esegue un primo blocco di istruzioni. Altrimenti, se il secondo valore è vero, esegue un secondo blocco di istruzioni. Se nessuno dei valori è vero esegue l'ultimo blocco di istruzioni.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://it.wikipedia.org/wiki/Ciclo_for";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "fai";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "ripeti %1 volte";
Blockly.Msg.CONTROLS_REPEAT_TITLE_REPEAT = "ripeti";
Blockly.Msg.CONTROLS_REPEAT_TITLE_TIMES = "volte";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Esegue alcune istruzione diverse volte.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "ripeti fino a che";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "ripeti mentre";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Finché un valore è falso, esegue alcune istruzioni.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Finché un valore è vero, esegue alcune istruzioni.";
Blockly.Msg.DELETE_BLOCK = "Cancella blocco";
Blockly.Msg.DELETE_X_BLOCKS = "Cancella %1 blocchi";
Blockly.Msg.DISABLE_BLOCK = "Disattiva blocco";
Blockly.Msg.DUPLICATE_BLOCK = "Duplica";
Blockly.Msg.ENABLE_BLOCK = "Attiva blocco";
Blockly.Msg.EXPAND_ALL = "Espandi blocchi";
Blockly.Msg.EXPAND_BLOCK = "Espandi blocco";
Blockly.Msg.EXPANSION_ELEVATION_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_ELEVATION_TOOLTI = "Gripper Servo Elevation";  // untranslated
Blockly.Msg.EXPANSION_EXP1OFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1OFF_TOOLTIP = "Turn Expansion 1 +3.3V Power Off";  // untranslated
Blockly.Msg.EXPANSION_EXP1ON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1ON_TOOLTIP = "Turn Expansion 1 +3.3V Power On";  // untranslated
Blockly.Msg.EXPANSION_EXP1_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1_OFF = "expansion 1 power off";  // untranslated
Blockly.Msg.EXPANSION_EXP1_ON = "expansion 1 power on";  // untranslated
Blockly.Msg.EXPANSION_EXP1_TOOLTIP = "Expansion 1 Power Control";  // untranslated
Blockly.Msg.EXPANSION_EXP2OFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2OFF_TOOLTIP = "Turn Expansion 2 +3.3V Power Off";  // untranslated
Blockly.Msg.EXPANSION_EXP2ON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2ON_TOOLTIP = "Turn Expansion 2 +3.3V Power On";  // untranslated
Blockly.Msg.EXPANSION_EXP2_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2_OFF = "expansion 2 power off";  // untranslated
Blockly.Msg.EXPANSION_EXP2_ON = "expansion 2 power on";  // untranslated
Blockly.Msg.EXPANSION_EXP2_TOOLTIP = "Expansion 2 Power Control";  // untranslated
Blockly.Msg.EXPANSION_GRIPPER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_GRIPPER_TOOLTIP = "Gripper Servo Open/Close";  // untranslated
Blockly.Msg.EXPANSION_SERVOOFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVOOFF_TOOLTIP = "Turn Servo +5V Power Off";  // untranslated
Blockly.Msg.EXPANSION_SERVOON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVOON_TOOLTIP = "Turn Servo +5V Power On";  // untranslated
Blockly.Msg.EXPANSION_SERVO_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVO_OFF = "servo power off";  // untranslated
Blockly.Msg.EXPANSION_SERVO_ON = "servo power on";  // untranslated
Blockly.Msg.EXPANSION_SERVO_TOOLTIP = "Servo Power Control";  // untranslated
Blockly.Msg.EXTERNAL_INPUTS = "Ingressi esterni";
Blockly.Msg.HELP = "Aiuto";
Blockly.Msg.INLINE_INPUTS = "Ingressi in linea";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://en.wikipedia.org/wiki/Linked_list#Empty_lists";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "crea lista vuota";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Restituisce una lista, di lunghezza 0, contenente nessun record di dati";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "lista";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Aggiungi, rimuovi o riordina le sezioni per riconfigurare il blocco lista.";
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "crea lista con";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Aggiunge un elemento alla lista.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Crea una lista con un certo numero di elementi.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "primo";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "# dalla fine";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET = "prendi";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "prendi e rimuovi";
Blockly.Msg.LISTS_GET_INDEX_LAST = "ultimo";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "casuale";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "rimuovi";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Restituisce il primo elemento in una lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Restituisce l'elemento nella posizione indicata della lista. 1 corrisponde all'ultimo elemento.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Restituisce l'elemento nella posizione indicata della lista. 1 corrisponde al primo elemento della lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Restituisce l'ultimo elemento in una lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Restituisce un elemento casuale in una lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Rimuove e restituisce il primo elemento in una lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Rimuove e restituisce l'elemento nella posizione indicata in una lista. 1 corrisponde all'ultimo elemento.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Rimuove e restituisce l'elemento nella posizione indicata in una lista. 1 corrisponde al primo elemento.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Restituisce e rimuove l'ultimo elemento in una lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Restituisce e rimuove un elemento casuale in una lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Rimuove il primo elemento in una lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Rimuove l'elemento nella posizione indicata in una lista. 1 corrisponde all'ultimo elemento.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Rimuove l'elemento nella posizione indicata in una lista. 1 corrisponde al primo elemento.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Rimuove l'ultimo elemento in una lista.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Rimuove un elemento casuale in una lista.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "da # dalla fine";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "fino a #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "dagli ultimi";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#Getting_a_sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "prendi sotto-lista dall'inizio";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "prendi sotto-lista da # dalla fine";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "prendi sotto-lista da #";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Crea una copia della porzione specificata di una lista.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "trova la prima occorrenza dell'elemento";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#Getting_Items_from_a_List";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "trova l'ultima occorrenza dell'elemento";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Restituisce l'indice della prima/ultima occorrenza dell'elemento nella lista. Restituisce 0 se il testo non viene trovato.";
Blockly.Msg.LISTS_INLIST = "nella lista";
Blockly.Msg.LISTS_IS_EMPTY_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#is_empty";  // untranslated
Blockly.Msg.LISTS_IS_EMPTY_TITLE = "%1 è vuota";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#length_of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "lunghezza di %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Restituisce la lunghezza della lista";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#create_list_with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "crea una lista con l'elemento %1 ripetuto %2 volte";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Crea una lista costituita dal valore indicato ripetuto per il numero di volte specificato.";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#in_list_..._set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "come";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "inserisci in";
Blockly.Msg.LISTS_SET_INDEX_SET = "imposta";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Inserisci l'elemento all'inizio della lista.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Inserisci l'elemento nella posizione indicata in una lista. #1 corrisponde all'ultimo elemento.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Inserisci un elemento nella posizione indicata in una lista. #1 corrisponde al primo elemento.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Aggiungi un elemento alla fine di una lista";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Inserisce l'elemento casualmente in una lista.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Imposta il primo elemento in una lista.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Imposta l'elemento nella posizione indicata di una lista. 1 corrisponde all'ultimo elemento.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Imposta l'elemento nella posizione indicata di una lista. 1 corrisponde al primo elemento.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Imposta l'ultimo elemento in una lista.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Imposta un elemento casuale in una lista.";
Blockly.Msg.LISTS_TOOLTIP = "Restituisce vero se la lista è vuota.";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "falso";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Restituisce vero o falso.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "vero";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://it.wikipedia.org/wiki/Disuguaglianza";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Restituisce vero se gli input sono uno uguale all'altro.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Restituisce vero se il primo input è maggiore o uguale al secondo.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Restituisce uguale se il primo input è maggiore o uguale al secondo input.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Restituisce vero se il primo input è minore del secondo.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Restituisce vero se il primo input è minore o uguale al secondo.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Restituisce vero se gli input non sono uno uguale all'altro.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "non %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Restituisce vero se l'input è falso. Restituisce falso se l'input è vero.";
Blockly.Msg.LOGIC_NULL = "nullo";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Restituisce valore nullo.";
Blockly.Msg.LOGIC_OPERATION_AND = "e";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "o";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Restituisce vero se entrambi gli input sono veri.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Restituisce vero se almeno uno degli input è vero.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "se falso";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "se vero";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Verifica la condizione in 'test'. Se questa è vera restituisce il valore 'se vero' altrimenti restituisce il valore 'se falso'.";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://it.wikipedia.org/wiki/Aritmetica";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Restituisce la somma dei due numeri.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Restituisce il quoziente dei due numeri.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Restituisce la differenza dei due numeri.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MODULO = "Return the remainder of the division operation.";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Restituisce il prodotto dei due numeri.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Restituisce il primo numero elevato alla potenza del secondo numero.";
Blockly.Msg.MATH_BITWISE_AND = "&";  // untranslated
Blockly.Msg.MATH_BITWISE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_BITWISE_OR = "|";  // untranslated
Blockly.Msg.MATH_BITWISE_TOOLTIP = "Bitwise Operations";  // untranslated
Blockly.Msg.MATH_BITWISE_XOR = "^";  // untranslated
Blockly.Msg.MATH_CHANGE_HELPURL = "https://it.wikipedia.org/wiki/Addizione";
Blockly.Msg.MATH_CHANGE_INPUT_BY = "di";
Blockly.Msg.MATH_CHANGE_TITLE_CHANGE = "cambia";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Aggiunge un numero alla variabile '%1'.";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://it.wikipedia.org/wiki/Costante_matematica";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Restituisce una delle costanti comuniː π (3.141…), e (2.718…), φ (1.618…), radq(2) (1.414…), radq(½) (0.707…) o ∞ (infinito).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "costringi %1 da %2 a %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Costringe un numero all'interno dei limiti indicati (compresi).";
Blockly.Msg.MATH_DIVISION_SYMBOL = "/";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "è divisibile per";
Blockly.Msg.MATH_IS_EVEN = "è pari";
Blockly.Msg.MATH_IS_NEGATIVE = "è negativo";
Blockly.Msg.MATH_IS_ODD = "è dispari";
Blockly.Msg.MATH_IS_POSITIVE = "è positivo";
Blockly.Msg.MATH_IS_PRIME = "è primo";
Blockly.Msg.MATH_IS_TOOLTIP = "Verifica se un numero è pari, dispari, primo, intero, positivo, negativo o se è divisibile per un certo numero. Restituisce vero o falso.";
Blockly.Msg.MATH_IS_WHOLE = "è intero";
Blockly.Msg.MATH_MODULO_HELPURL = "https://it.wikipedia.org/wiki/Resto";
Blockly.Msg.MATH_MODULO_SYMBOL = "%";  // untranslated
Blockly.Msg.MATH_MODULO_TITLE = "resto di %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Restituisce il resto della divisione di due numeri.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "*";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://it.wikipedia.org/wiki/Numero";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "Un numero.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "media della lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "massimo della lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "mediana della lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "minimo della lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "mode della lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "elemento casuale della lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "deviazione standard della lista";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "somma la lista";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Restituisce la media (media aritmetica) dei valori numerici nella lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Restituisce il più grande numero della lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Restituisce il valore mediano della lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Restituisce il più piccolo numero della lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Restituisce una lista degli elementi più frequenti nella lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Restituisce un elemento casuale della lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Restituisce la deviazione standard della lista.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Restituisce la somma si tutti i numeri nella lista.";
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://it.wikipedia.org/wiki/Numeri_pseudo-casuali";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "frazione casuale";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Restituisce una frazione compresa fra 0.0 (incluso) e 1.0 (escluso).";
Blockly.Msg.MATH_RANDOM_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://it.wikipedia.org/wiki/Numeri_pseudo-casuali";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "intero casuale da %1 a %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Restituisce un numero intero casuale compreso tra i due limiti indicati (inclusi).";
Blockly.Msg.MATH_RANDOM_TITLE = "Random Number (0-99)";  // untranslated
Blockly.Msg.MATH_RANDOM_TOOLTIP = "Return Random Number";  // untranslated
Blockly.Msg.MATH_ROUND_HELPURL = "https://it.wikipedia.org/wiki/Arrotondamento";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "arrotonda";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "arrotonda verso il basso";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "arrotonda verso l'alto";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Arrotonda un numero verso l'alto o verso il basso.";
Blockly.Msg.MATH_SHIFT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_SHIFT_LEFT = "<<";  // untranslated
Blockly.Msg.MATH_SHIFT_RIGHT = ">>";  // untranslated
Blockly.Msg.MATH_SHIFT_TOOLTIP = "Bit Shift Operations";  // untranslated
Blockly.Msg.MATH_SINGLE_HELPURL = "https://it.wikipedia.org/wiki/Radice_quadrata";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "assoluto";
Blockly.Msg.MATH_SINGLE_OP_NEGATION = "negate";  // untranslated
Blockly.Msg.MATH_SINGLE_OP_ROOT = "radice quadrata";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Restituisce il valore assoluto del numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Restituisce e elevato alla potenza del numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Restituisce il logaritmo naturale del numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Restituisce il logaritmo in base 10 del numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Restituisce l'opposto del numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Restituisce 10 elevato alla potenza del numero.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Restituisce la radice quadrata del numero.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://it.wikipedia.org/wiki/Funzione_trigonometrica";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Restituisce l'arco-coseno di un numero.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Restituisce l'arco-seno di un numero.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Restituisce l'arco-tangente di un numero.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Restituisce il coseno di un angolo espresso in gradi (non radianti).";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Restituisce il seno di un angolo espresso in gradi (non radianti).";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Restituisce la tangente di un angolo espresso in gradi (non radianti).";
Blockly.Msg.ME = "Me";
Blockly.Msg.MULTIMEDIA_DISPLAYBMP_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_DISPLAYBMP_TOOLTIP = "Display BMP File on OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_DOUPDATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_DOUPDATE_TOOLTIP = "Do an Update to the OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_HIGH = "volume high";  // untranslated
Blockly.Msg.MULTIMEDIA_LOW = "volume low";  // untranslated
Blockly.Msg.MULTIMEDIA_MEDIUM = "volume medium";  // untranslated
Blockly.Msg.MULTIMEDIA_MUTE = "volume mute";  // untranslated
Blockly.Msg.MULTIMEDIA_PLAYWAV_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_PLAYWAV_TOOLTIP = "Play WAV File on Jade Robot";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_TITLE = "playing active";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_TOOLTIP = "Return Not Zero if WAV File still playing";  // untranslated
Blockly.Msg.MULTIMEDIA_STOPUPDATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_STOPUPDATE_TOOLTIP = "Stop Updating the OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_VOLUME_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_VOLUME_TOOLTIP = "Set Speaker Volume";  // untranslated
Blockly.Msg.NEW_VARIABLE = "Nuova variabile...";
Blockly.Msg.NEW_VARIABLE_TITLE = "Nome della nuova variabile:";
Blockly.Msg.OLED_COLOR_BLACK = "color black";  // untranslated
Blockly.Msg.OLED_COLOR_GREEN = "color green";  // untranslated
Blockly.Msg.OLED_COLOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.OLED_COLOR_TOOLTIP = "Set OLED Draw Color";  // untranslated
Blockly.Msg.OLED_DRAW_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.OLED_DRAW_LINE = "draw line";  // untranslated
Blockly.Msg.OLED_DRAW_RECT = "draw rectangle";  // untranslated
Blockly.Msg.OLED_DRAW_TOOLTIP = "Draw from Cursor to End";  // untranslated
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "consenti dichiarazioni";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "conː";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "";  // untranslated
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://it.wikipedia.org/wiki/Funzione_(informatica)";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Esegue la funzione definita dall'utente '%1'.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://it.wikipedia.org/wiki/Funzione_(informatica)";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Esegue la funzione definita dall'utente '%1' ed usa il suo output.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "conː";
Blockly.Msg.PROCEDURES_CREATE_DO = "Crea '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "fai qualcosa";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "per";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Crea una funzione senza output.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = "functionName";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "ritorna";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Crea una funzione con un output.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Attenzioneː Questa funzione ha parametri duplicati.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Evidenzia definizione di funzione";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "Se un valore è vero allora restituisce un secondo valore.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Attenzioneː Questo blocco può essere usato solo all'interno di una definizione di funzione.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "nome inputː";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Aggiungi un input alla funzione.";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "input";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Aggiungi, rimuovi o riordina input alla funzione.";
Blockly.Msg.REMOVE_COMMENT = "Rimuovi commento";
Blockly.Msg.RENAME_VARIABLE = "Rinomina variabile...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Rinomina tutte le variabili '%1' in:";
Blockly.Msg.ROBOT_LED_FLASH = "led flash";  // untranslated
Blockly.Msg.ROBOT_LED_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.ROBOT_LED_OFF = "led off";  // untranslated
Blockly.Msg.ROBOT_LED_ON = "led on";  // untranslated
Blockly.Msg.ROBOT_LED_TOOLTIP = "Set LED";  // untranslated
Blockly.Msg.SENSOR_BATTERY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_BATTERY_TITLE = "battery level";  // untranslated
Blockly.Msg.SENSOR_BATTERY_TOOLTIP = "Return Battery Level";  // untranslated
Blockly.Msg.SENSOR_BUTTON_DOWN = "button down pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_ENTER = "button enter pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_BUTTON_LEFT = "button left pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_RIGHT = "button right pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_TOOLTIP = "Return Button State";  // untranslated
Blockly.Msg.SENSOR_BUTTON_UP = "button up pressed";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_LEFT = "light left";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_REAR = "light rear";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_RIGHT = "light right";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_TOOLTIP = "Returns Light Sensor.";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_LEFT = "line left";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_MIDDLE = "line middle";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_RIGHT = "line right";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_TOOLTIP = "Returns Line Sensor.";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_LEFTFRONT = "object left front";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_LEFTSIDE = "object left side";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_REAR = "object rear";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_RIGHTFRONT = "object right front";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_RIGHTSIDE = "object right side";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_TOOLTIP = "Returns Object Sensor.";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_BLUE = "spectrometer blue";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_GREEN = "spectrometer green";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_IR880 = "spectrometer 880nm";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_IR940 = "spectrometer 940nm";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_RED = "spectrometer red";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_TOOLTIP = "Return Spectrometer Reading";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_YELLOW = "spectrometer yellow";  // untranslated
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "aggiungi il testo";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "a";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Aggiunge del testo alla variabile '%1'.";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Adjusting_text_case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "in minuscolo";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "con Iniziali Maiuscole";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "in MAIUSCOLO";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Restituisce una copia del testo in un diverso formato maiuscole/minuscole.";
Blockly.Msg.TEXT_CHARAT_FIRST = "prendi la prima lettera";
Blockly.Msg.TEXT_CHARAT_FROM_END = "prendi la lettera # dalla fine";
Blockly.Msg.TEXT_CHARAT_FROM_START = "prendi la lettera #";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Extracting_text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "nel testo";
Blockly.Msg.TEXT_CHARAT_LAST = "prendi l'ultima lettera";
Blockly.Msg.TEXT_CHARAT_RANDOM = "prendi lettera casuale";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Restituisce la lettera nella posizione indicata.";
Blockly.Msg.TEXT_CLEARDISPLAY_TOOLTIP = "Clear OLED Display";  // untranslated
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Aggiungi un elemento al testo.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "unisci";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Aggiungi, rimuovi o riordina le sezioni per riconfigurare questo blocco testo.";
Blockly.Msg.TEXT_DRAWNUMBER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_DRAWNUMBER_TOOLTIP = "Draw the specified number";  // untranslated
Blockly.Msg.TEXT_DRAWTEXT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_DRAWTEXT_TOOLTIP = "Draw the specified text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "alla lettera # dalla fine";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "alla lettera #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "all'ultima lettera";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Extracting_a_region_of_text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "nel testo";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "prendi sotto-stringa dalla prima lettera";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "prendi sotto-stringa dalla lettera # dalla fine";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "prendi sotto-stringa dalla lettera #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Restituisce la porzione di testo indicata.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Finding_text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "nel testo";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "trova la prima occorrenza del testo";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "trova l'ultima occorrenza del testo";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Restituisce l'indice della prima occorrenza del primo testo all'interno del secondo testo. Restituisce 0 se il testo non viene trovato.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Checking_for_empty_text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 è vuoto";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Restituisce vero se il testo fornito è vuoto.";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "crea testo con";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Crea un blocco di testo unendo un certo numero di elementi.";
Blockly.Msg.TEXT_LEFTMOTOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_LEFTMOTOR_TITLE = "Set Left Motor %1";  // untranslated
Blockly.Msg.TEXT_LEFTMOTOR_TOOLTIP = "Specify the Value for the Left Motor.";  // untranslated
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "lunghezza di %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Restituisce il numero di lettere (inclusi gli spazi) nel testo fornito.";
Blockly.Msg.TEXT_MOTORSFORWARD_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSFORWARD_TITLE = "Move Robot Forward";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_TITLE = "Turn Left";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_TOOLTIP = "Turn Robot Left";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_TITLE = "Robot Reverse";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_TOOLTIP = "Move Robot Backward";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_TITLE = "Turn Right";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_TOOLTIP = "Turn Robot Right";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_TITLE = "Stop Robot";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_TOOLTIP = "Stop Robot";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_TITLE = "Robot Stutter";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_TOOLTIP = "Robot Stutter";  // untranslated
Blockly.Msg.TEXT_OLEDCLEARDISPLAY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDCURSOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDCURSOR_TOOLTIP = "Set the Draw Position";  // untranslated
Blockly.Msg.TEXT_OLEDEND_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDEND_TOOLTIP = "Set the End Draw Position";  // untranslated
Blockly.Msg.TEXT_PRINT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "scrivi %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Scrive il testo, numero o altro valore indicato.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Getting_input_from_the_user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Richiedi un numero all'utente.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Richiede del testo da parte dell'utente.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "richiedi numero con messaggio";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "richiedi testo con messaggio";
Blockly.Msg.TEXT_RIGHTMOTOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_RIGHTMOTOR_TOOLTIP = "Specify the Value for the Right Motor.";  // untranslated
Blockly.Msg.TEXT_ROBOTDELAY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_ROBOTDELAY_TITLE = "Delay in ms %1";  // untranslated
Blockly.Msg.TEXT_SETMOTORS_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_SETMOTORS_TOOLTIP = "Specify the Value for the Motors.";  // untranslated
Blockly.Msg.TEXT_TEXT_HELPURL = "https://it.wikipedia.org/wiki/Stringa_(informatica)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "Una lettera, una parola o una linea di testo.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Trimming_%28removing%29_spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "rimuovi spazi da entrambi gli estremi";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "rimuovi spazi a sinistra";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "rimuovi spazi a destra";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Restituisce una copia del testo con gli spazi rimossi ad uno o entrambe le estremità.";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "elemento";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Crea 'imposta %1'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.VARIABLES_GET_TAIL = "";  // untranslated
Blockly.Msg.VARIABLES_GET_TITLE = "";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Restituisce il valore di una variabile.";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Crea 'prendi %1'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.VARIABLES_SET_TAIL = "a";
Blockly.Msg.VARIABLES_SET_TITLE = "imposta";
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Imposta questa variabile ad essere pari all'input.";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE;
Blockly.Msg.VARIABLES_SET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;