// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.lb');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "Bemierkung derbäisetzen";
Blockly.Msg.AUTH = "Please authorize this app to enable your work to be saved and to allow it to be shared by you.";  // untranslated
Blockly.Msg.CHANGE_VALUE_TITLE = "Wäert änneren:";
Blockly.Msg.CHAT = "Mat ärem Mataarbechter chatten an deem Dir an dës Këscht tippt!";
Blockly.Msg.COLLAPSE_ALL = "Collapse Blocks";  // untranslated
Blockly.Msg.COLLAPSE_BLOCK = "Block zesummeklappen";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "Faarf 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "Faarf 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "ratio";
Blockly.Msg.COLOUR_BLEND_TITLE = "mëschen";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Blends two colours together with a given ratio (0.0 - 1.0).";  // untranslated
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://en.wikipedia.org/wiki/Color";  // untranslated
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Wielt eng Faarf vun der Palette.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "zoufälleg Faarf";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Eng zoufälleg Faarf eraussichen.";
Blockly.Msg.COLOUR_RGB_BLUE = "blo";
Blockly.Msg.COLOUR_RGB_GREEN = "gréng";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "rout";
Blockly.Msg.COLOUR_RGB_TITLE = "fierwe mat";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Create a colour with the specified amount of red, green, and blue.  All values must be between 0 and 100.";  // untranslated
Blockly.Msg.COMMENT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.COMMENT_TITLE = "Program Comment";  // untranslated
Blockly.Msg.COMMENT_TOOLTIP = "Comment Text";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://code.google.com/p/blockly/wiki/Loops#Loop_Termination_Blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "break out of loop";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "continue with next iteration of loop";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Break out of the containing loop.";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Skip the rest of this loop, and continue with the next iteration.";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Warning: This block may only be used within a loop.";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST = "an der Lëscht";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST_TAIL = "";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_INPUT_ITEM = "fir all Element";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "For each item in a list, set the variable '%1' to the item, and then do some statements.";  // untranslated
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY = "vun %1 bis %2 mat %3";
Blockly.Msg.CONTROLS_FOR_INPUT_WITH = "count with";  // untranslated
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Have the variable %1 take on the values from the start number to the end number, counting by the specified interval, and do the specified blocks.";  // untranslated
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Add a condition to the if block.";  // untranslated
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Add a final, catch-all condition to the if block.";  // untranslated
Blockly.Msg.CONTROLS_IF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Add, remove, or reorder sections to reconfigure this if block.";  // untranslated
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "soss";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "else if";  // untranslated
Blockly.Msg.CONTROLS_IF_MSG_IF = "wann";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "If a value is true, then do some statements.";  // untranslated
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "If a value is true, then do the first block of statements.  Otherwise, do the second block of statements.";  // untranslated
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "If the first value is true, then do the first block of statements.  Otherwise, if the second value is true, do the second block of statements.";  // untranslated
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "If the first value is true, then do the first block of statements.  Otherwise, if the second value is true, do the second block of statements.  If none of the values are true, do the last block of statements.";  // untranslated
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "maachen";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "%1 mol widderhuelen";
Blockly.Msg.CONTROLS_REPEAT_TITLE_REPEAT = "widderhuelen";
Blockly.Msg.CONTROLS_REPEAT_TITLE_TIMES = "mol";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Do some statements several times.";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "widderhuele bis";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "repeat while";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "While a value is false, then do some statements.";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "While a value is true, then do some statements.";  // untranslated
Blockly.Msg.DELETE_BLOCK = "Block läschen";
Blockly.Msg.DELETE_X_BLOCKS = "%1 Bléck läschen";
Blockly.Msg.DISABLE_BLOCK = "Block desaktivéieren";
Blockly.Msg.DUPLICATE_BLOCK = "Duplizéieren";
Blockly.Msg.ENABLE_BLOCK = "Block aktivéieren";
Blockly.Msg.EXPAND_ALL = "Bléck opklappen";
Blockly.Msg.EXPAND_BLOCK = "Block opklappen";
Blockly.Msg.EXPANSION_ELEVATION_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_ELEVATION_TOOLTI = "Gripper Servo Elevation";  // untranslated
Blockly.Msg.EXPANSION_EXP1OFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1OFF_TOOLTIP = "Turn Expansion 1 +3.3V Power Off";  // untranslated
Blockly.Msg.EXPANSION_EXP1ON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1ON_TOOLTIP = "Turn Expansion 1 +3.3V Power On";  // untranslated
Blockly.Msg.EXPANSION_EXP1_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1_OFF = "expansion 1 power off";  // untranslated
Blockly.Msg.EXPANSION_EXP1_ON = "expansion 1 power on";  // untranslated
Blockly.Msg.EXPANSION_EXP1_TOOLTIP = "Expansion 1 Power Control";  // untranslated
Blockly.Msg.EXPANSION_EXP2OFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2OFF_TOOLTIP = "Turn Expansion 2 +3.3V Power Off";  // untranslated
Blockly.Msg.EXPANSION_EXP2ON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2ON_TOOLTIP = "Turn Expansion 2 +3.3V Power On";  // untranslated
Blockly.Msg.EXPANSION_EXP2_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2_OFF = "expansion 2 power off";  // untranslated
Blockly.Msg.EXPANSION_EXP2_ON = "expansion 2 power on";  // untranslated
Blockly.Msg.EXPANSION_EXP2_TOOLTIP = "Expansion 2 Power Control";  // untranslated
Blockly.Msg.EXPANSION_GRIPPER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_GRIPPER_TOOLTIP = "Gripper Servo Open/Close";  // untranslated
Blockly.Msg.EXPANSION_SERVOOFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVOOFF_TOOLTIP = "Turn Servo +5V Power Off";  // untranslated
Blockly.Msg.EXPANSION_SERVOON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVOON_TOOLTIP = "Turn Servo +5V Power On";  // untranslated
Blockly.Msg.EXPANSION_SERVO_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVO_OFF = "servo power off";  // untranslated
Blockly.Msg.EXPANSION_SERVO_ON = "servo power on";  // untranslated
Blockly.Msg.EXPANSION_SERVO_TOOLTIP = "Servo Power Control";  // untranslated
Blockly.Msg.EXTERNAL_INPUTS = "External Inputs";  // untranslated
Blockly.Msg.HELP = "Hëllef";
Blockly.Msg.INLINE_INPUTS = "Inline Inputs";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://en.wikipedia.org/wiki/Linked_list#Empty_lists";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "create empty list";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Returns a list, of length 0, containing no data records";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "Lëscht";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Add, remove, or reorder sections to reconfigure this list block.";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "create list with";  // untranslated
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "En Element op d'Lëscht derbäisetzen.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Create a list with any number of items.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_FIRST = "éischt";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "# vum Schluss";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";
Blockly.Msg.LISTS_GET_INDEX_GET = "get";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "get and remove";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_LAST = "lescht";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "Zoufall";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "ewechhuelen";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Returns the first item in a list.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "Returns the item at the specified position in a list.  #1 is the last item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "Returns the item at the specified position in a list.  #1 is the first item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Returns the last item in a list.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Schéckt en zoufällegt Element aus enger Lëscht zréck.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Removes and returns the first item in a list.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "Removes and returns the item at the specified position in a list.  #1 is the last item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "Removes and returns the item at the specified position in a list.  #1 is the first item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Removes and returns the last item in a list.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Removes and returns a random item in a list.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Removes the first item in a list.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "Removes the item at the specified position in a list.  #1 is the last item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "Removes the item at the specified position in a list.  #1 is the first item.";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Hëlt dat lescht Element aus enger Lëscht eraus.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Hëlt en zoufällegt Element aus enger Lëscht eraus.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "to # from end";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "to #";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "to last";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#Getting_a_sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "get sub-list from first";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "get sub-list from # from end";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "get sub-list from #";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Creates a copy of the specified portion of a list.";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_FIRST = "find first occurrence of item";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#Getting_Items_from_a_List";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "find last occurrence of item";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Returns the index of the first/last occurrence of the item in the list.  Returns 0 if text is not found.";  // untranslated
Blockly.Msg.LISTS_INLIST = "an der Lëscht";
Blockly.Msg.LISTS_IS_EMPTY_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#is_empty";  // untranslated
Blockly.Msg.LISTS_IS_EMPTY_TITLE = "%1 ass eidel";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#length_of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "Längt vu(n) %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Returns the length of a list.";  // untranslated
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#create_list_with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "create list with item %1 repeated %2 times";  // untranslated
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Creates a list consisting of the given value repeated the specified number of times.";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#in_list_..._set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "als";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "asetzen op";
Blockly.Msg.LISTS_SET_INDEX_SET = "set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Inserts the item at the start of a list.";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "Inserts the item at the specified position in a list.  #1 is the last item.";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "Inserts the item at the specified position in a list.  #1 is the first item.";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Setzt d'Element um Ënn vun enger Lëscht derbäi.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Setzt d'Element op eng zoufälleg Plaz an d'Lëscht derbäi.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Sets the first item in a list.";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "Sets the item at the specified position in a list.  #1 is the last item.";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "Sets the item at the specified position in a list.  #1 is the first item.";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Sets the last item in a list.";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Setzt en zuofällegt Element an eng Lëscht.";
Blockly.Msg.LISTS_TOOLTIP = "Returns true if the list is empty.";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "falsch";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Schéckt entweder richteg oder falsch zréck.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "wouer";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Return true if both inputs equal each other.";  // untranslated
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Return true if the first input is greater than the second input.";  // untranslated
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Return true if the first input is greater than or equal to the second input.";  // untranslated
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Return true if the first input is smaller than the second input.";  // untranslated
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Return true if the first input is smaller than or equal to the second input.";  // untranslated
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Return true if both inputs are not equal to each other.";  // untranslated
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "net %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Returns true if the input is false.  Returns false if the input is true.";  // untranslated
Blockly.Msg.LOGIC_NULL = "null";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Returns null.";  // untranslated
Blockly.Msg.LOGIC_OPERATION_AND = "an";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "oder";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Return true if both inputs are true.";  // untranslated
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Return true if at least one of the inputs is true.";  // untranslated
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "wa falsch";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "wa wouer";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Check the condition in 'test'. If the condition is true, returns the 'if true' value; otherwise returns the 'if false' value.";  // untranslated
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Gëtt d'Zomme vun zwou Zuelen.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Return the quotient of the two numbers.";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Return the difference of the two numbers.";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MODULO = "Return the remainder of the division operation.";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "D'Produkt vun den zwou Zuelen zréckginn.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Return the first number raised to the power of the second number.";  // untranslated
Blockly.Msg.MATH_BITWISE_AND = "&";  // untranslated
Blockly.Msg.MATH_BITWISE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_BITWISE_OR = "|";  // untranslated
Blockly.Msg.MATH_BITWISE_TOOLTIP = "Bitwise Operations";  // untranslated
Blockly.Msg.MATH_BITWISE_XOR = "^";  // untranslated
Blockly.Msg.MATH_CHANGE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_CHANGE_INPUT_BY = "ëm";
Blockly.Msg.MATH_CHANGE_TITLE_CHANGE = "änneren";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Add a number to variable '%1'.";  // untranslated
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Return one of the common constants: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), or ∞ (infinity).";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";
Blockly.Msg.MATH_CONSTRAIN_TITLE = "constrain %1 low %2 high %3";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Constrain a number to be between the specified limits (inclusive).";  // untranslated
Blockly.Msg.MATH_DIVISION_SYMBOL = "/";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "is divisible by";  // untranslated
Blockly.Msg.MATH_IS_EVEN = "ass gerued";
Blockly.Msg.MATH_IS_NEGATIVE = "ass negativ";
Blockly.Msg.MATH_IS_ODD = "ass net gerued";
Blockly.Msg.MATH_IS_POSITIVE = "ass positiv";
Blockly.Msg.MATH_IS_PRIME = "ass eng Primzuel";
Blockly.Msg.MATH_IS_TOOLTIP = "Check if a number is an even, odd, prime, whole, positive, negative, or if it is divisible by certain number.  Returns true or false.";  // untranslated
Blockly.Msg.MATH_IS_WHOLE = "ass eng ganz Zuel";
Blockly.Msg.MATH_MODULO_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_MODULO_SYMBOL = "%";  // untranslated
Blockly.Msg.MATH_MODULO_TITLE = "Rescht vu(n) %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Return the remainder from dividing the two numbers.";  // untranslated
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "*";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_NUMBER_TOOLTIP = "Eng Zuel.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "Duerchschnëtt vun der Lëscht";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "Maximum aus der Lëscht";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "median of list";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "min of list";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "modes of list";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "zoufällegt Element vun enger Lëscht";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "standard deviation of list";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "sum of list";  // untranslated
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Return the average (arithmetic mean) of the numeric values in the list.";  // untranslated
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Schéckt de gréisste Wäert aus enger Lëscht zréck.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Return the median number in the list.";  // untranslated
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Return the smallest number in the list.";  // untranslated
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Return a list of the most common item(s) in the list.";  // untranslated
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Return a random element from the list.";  // untranslated
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Return the standard deviation of the list.";  // untranslated
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Return the sum of all the numbers in the list.";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "random fraction";  // untranslated
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Return a random fraction between 0.0 (inclusive) and 1.0 (exclusive).";  // untranslated
Blockly.Msg.MATH_RANDOM_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_RANDOM_INT_TITLE = "zoufälleg ganz Zuel tëscht %1 a(n) %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Return a random integer between the two specified limits, inclusive.";  // untranslated
Blockly.Msg.MATH_RANDOM_TITLE = "Random Number (0-99)";  // untranslated
Blockly.Msg.MATH_RANDOM_TOOLTIP = "Return Random Number";  // untranslated
Blockly.Msg.MATH_ROUND_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "opronnen";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "ofronnen";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "opronnen";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Eng Zuel op- oder ofronnen.";
Blockly.Msg.MATH_SHIFT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_SHIFT_LEFT = "<<";  // untranslated
Blockly.Msg.MATH_SHIFT_RIGHT = ">>";  // untranslated
Blockly.Msg.MATH_SHIFT_TOOLTIP = "Bit Shift Operations";  // untranslated
Blockly.Msg.MATH_SINGLE_HELPURL = "https://en.wikipedia.org/wiki/Square_root";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "absolut";
Blockly.Msg.MATH_SINGLE_OP_NEGATION = "negate";  // untranslated
Blockly.Msg.MATH_SINGLE_OP_ROOT = "Quadratwuerzel";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Return the absolute value of a number.";  // untranslated
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Return e to the power of a number.";  // untranslated
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Return the natural logarithm of a number.";  // untranslated
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Return the base 10 logarithm of a number.";  // untranslated
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Return the negation of a number.";  // untranslated
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Return 10 to the power of a number.";  // untranslated
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Return the square root of a number.";  // untranslated
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";  // untranslated
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Return the arccosine of a number.";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Return the arcsine of a number.";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Return the arctangent of a number.";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Return the cosine of a degree (not radian).";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Return the sine of a degree (not radian).";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Return the tangent of a degree (not radian).";  // untranslated
Blockly.Msg.ME = "Mech";
Blockly.Msg.MULTIMEDIA_DISPLAYBMP_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_DISPLAYBMP_TOOLTIP = "Display BMP File on OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_DOUPDATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_DOUPDATE_TOOLTIP = "Do an Update to the OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_HIGH = "volume high";  // untranslated
Blockly.Msg.MULTIMEDIA_LOW = "volume low";  // untranslated
Blockly.Msg.MULTIMEDIA_MEDIUM = "volume medium";  // untranslated
Blockly.Msg.MULTIMEDIA_MUTE = "volume mute";  // untranslated
Blockly.Msg.MULTIMEDIA_PLAYWAV_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_PLAYWAV_TOOLTIP = "Play WAV File on Jade Robot";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_TITLE = "playing active";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_TOOLTIP = "Return Not Zero if WAV File still playing";  // untranslated
Blockly.Msg.MULTIMEDIA_STOPUPDATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_STOPUPDATE_TOOLTIP = "Stop Updating the OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_VOLUME_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_VOLUME_TOOLTIP = "Set Speaker Volume";  // untranslated
Blockly.Msg.NEW_VARIABLE = "Nei Variabel...";
Blockly.Msg.NEW_VARIABLE_TITLE = "Neie variabelen Numm:";
Blockly.Msg.OLED_COLOR_BLACK = "color black";  // untranslated
Blockly.Msg.OLED_COLOR_GREEN = "color green";  // untranslated
Blockly.Msg.OLED_COLOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.OLED_COLOR_TOOLTIP = "Set OLED Draw Color";  // untranslated
Blockly.Msg.OLED_DRAW_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.OLED_DRAW_LINE = "draw line";  // untranslated
Blockly.Msg.OLED_DRAW_RECT = "draw rectangle";  // untranslated
Blockly.Msg.OLED_DRAW_TOOLTIP = "Draw from Cursor to End";  // untranslated
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "allow statements";  // untranslated
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "mat:";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "";  // untranslated
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Run the user-defined function '%1'.";  // untranslated
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Run the user-defined function '%1' and use its output.";  // untranslated
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "with:";  // untranslated
Blockly.Msg.PROCEDURES_CREATE_DO = "Create '%1'";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "eppes maachen";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Creates a function with no output.";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = "functionName";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "zréck";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Creates a function with an output.";  // untranslated
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Warning: This function has duplicate parameters.";  // untranslated
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Highlight function definition";  // untranslated
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "If true, then return value from function.";  // untranslated
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Warning: This block may be used only within a function definition.";  // untranslated
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "input name:";  // untranslated
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Add an input to the function.";  // untranslated
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "inputs";  // untranslated
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Add, remove, or reorder inputs to this function.";  // untranslated
Blockly.Msg.REMOVE_COMMENT = "Bemierkunge ewechhuelen";
Blockly.Msg.RENAME_VARIABLE = "Variabel ëmbenennen...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "All '%1' Variabelen ëmbenennen op:";
Blockly.Msg.ROBOT_LED_FLASH = "led flash";  // untranslated
Blockly.Msg.ROBOT_LED_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.ROBOT_LED_OFF = "led off";  // untranslated
Blockly.Msg.ROBOT_LED_ON = "led on";  // untranslated
Blockly.Msg.ROBOT_LED_TOOLTIP = "Set LED";  // untranslated
Blockly.Msg.SENSOR_BATTERY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_BATTERY_TITLE = "battery level";  // untranslated
Blockly.Msg.SENSOR_BATTERY_TOOLTIP = "Return Battery Level";  // untranslated
Blockly.Msg.SENSOR_BUTTON_DOWN = "button down pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_ENTER = "button enter pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_BUTTON_LEFT = "button left pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_RIGHT = "button right pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_TOOLTIP = "Return Button State";  // untranslated
Blockly.Msg.SENSOR_BUTTON_UP = "button up pressed";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_LEFT = "light left";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_REAR = "light rear";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_RIGHT = "light right";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_TOOLTIP = "Returns Light Sensor.";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_LEFT = "line left";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_MIDDLE = "line middle";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_RIGHT = "line right";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_TOOLTIP = "Returns Line Sensor.";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_LEFTFRONT = "object left front";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_LEFTSIDE = "object left side";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_REAR = "object rear";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_RIGHTFRONT = "object right front";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_RIGHTSIDE = "object right side";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_TOOLTIP = "Returns Object Sensor.";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_BLUE = "spectrometer blue";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_GREEN = "spectrometer green";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_IR880 = "spectrometer 880nm";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_IR940 = "spectrometer 940nm";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_RED = "spectrometer red";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_TOOLTIP = "Return Spectrometer Reading";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_YELLOW = "spectrometer yellow";  // untranslated
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "Text drunhänken";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_modification";
Blockly.Msg.TEXT_APPEND_TO = "to";  // untranslated
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Append some text to variable '%1'.";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Adjusting_text_case";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "to lower case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "to Title Case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "to UPPER CASE";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Return a copy of the text in a different case.";  // untranslated
Blockly.Msg.TEXT_CHARAT_FIRST = "get first letter";  // untranslated
Blockly.Msg.TEXT_CHARAT_FROM_END = "get letter # from end";  // untranslated
Blockly.Msg.TEXT_CHARAT_FROM_START = "get letter #";  // untranslated
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Extracting_text";
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "am Text";
Blockly.Msg.TEXT_CHARAT_LAST = "get last letter";  // untranslated
Blockly.Msg.TEXT_CHARAT_RANDOM = "get random letter";  // untranslated
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Returns the letter at the specified position.";  // untranslated
Blockly.Msg.TEXT_CLEARDISPLAY_TOOLTIP = "Clear OLED Display";  // untranslated
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "En Element bei den Text derbäisetzen.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "join";  // untranslated
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Add, remove, or reorder sections to reconfigure this text block.";  // untranslated
Blockly.Msg.TEXT_DRAWNUMBER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_DRAWNUMBER_TOOLTIP = "Draw the specified number";  // untranslated
Blockly.Msg.TEXT_DRAWTEXT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_DRAWTEXT_TOOLTIP = "Draw the specified text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "to letter # from end";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "bis de Buschtaf #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "op de leschte Buschtaw";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Extracting_a_region_of_text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "am Text";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "get substring from first letter";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "get substring from letter # from end";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "get substring from letter #";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Returns a specified portion of the text.";  // untranslated
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Finding_text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "am Text";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "find first occurrence of text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "find last occurrence of text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Returns the index of the first/last occurrence of first text in the second text.  Returns 0 if text is not found.";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Checking_for_empty_text";
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 ass eidel";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Returns true if the provided text is empty.";  // untranslated
Blockly.Msg.TEXT_JOIN_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_creation";
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "create text with";  // untranslated
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Create a piece of text by joining together any number of items.";  // untranslated
Blockly.Msg.TEXT_LEFTMOTOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_LEFTMOTOR_TITLE = "Set Left Motor %1";  // untranslated
Blockly.Msg.TEXT_LEFTMOTOR_TOOLTIP = "Specify the Value for the Left Motor.";  // untranslated
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "Längt vu(n) %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Returns the number of letters (including spaces) in the provided text.";  // untranslated
Blockly.Msg.TEXT_MOTORSFORWARD_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSFORWARD_TITLE = "Move Robot Forward";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_TITLE = "Turn Left";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_TOOLTIP = "Turn Robot Left";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_TITLE = "Robot Reverse";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_TOOLTIP = "Move Robot Backward";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_TITLE = "Turn Right";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_TOOLTIP = "Turn Robot Right";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_TITLE = "Stop Robot";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_TOOLTIP = "Stop Robot";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_TITLE = "Robot Stutter";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_TOOLTIP = "Robot Stutter";  // untranslated
Blockly.Msg.TEXT_OLEDCLEARDISPLAY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDCURSOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDCURSOR_TOOLTIP = "Set the Draw Position";  // untranslated
Blockly.Msg.TEXT_OLEDEND_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDEND_TOOLTIP = "Set the End Draw Position";  // untranslated
Blockly.Msg.TEXT_PRINT_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Printing_text";
Blockly.Msg.TEXT_PRINT_TITLE = "%1 drécken";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Print the specified text, number or other value.";  // untranslated
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Getting_input_from_the_user";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Prompt for user for a number.";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Freet de Benotzer en Text.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "prompt for number with message";  // untranslated
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "prompt for text with message";  // untranslated
Blockly.Msg.TEXT_RIGHTMOTOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_RIGHTMOTOR_TOOLTIP = "Specify the Value for the Right Motor.";  // untranslated
Blockly.Msg.TEXT_ROBOTDELAY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_ROBOTDELAY_TITLE = "Delay in ms %1";  // untranslated
Blockly.Msg.TEXT_SETMOTORS_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_SETMOTORS_TOOLTIP = "Specify the Value for the Motors.";  // untranslated
Blockly.Msg.TEXT_TEXT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_TEXT_TOOLTIP = "E Buschtaf, e Wuert oder eng Textzeil.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Trimming_%28removing%29_spaces";
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "trim spaces from both sides of";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "trim spaces from left side of";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "trim spaces from right side of";  // untranslated
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Return a copy of the text with spaces removed from one or both ends.";  // untranslated
Blockly.Msg.VARIABLES_DEFAULT_NAME = "Element";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Create 'set %1'";  // untranslated
Blockly.Msg.VARIABLES_GET_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.VARIABLES_GET_TAIL = "";  // untranslated
Blockly.Msg.VARIABLES_GET_TITLE = "";  // untranslated
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Returns the value of this variable.";  // untranslated
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Create 'get %1'";  // untranslated
Blockly.Msg.VARIABLES_SET_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.VARIABLES_SET_TAIL = "to";  // untranslated
Blockly.Msg.VARIABLES_SET_TITLE = "set";  // untranslated
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Sets this variable to be equal to the input.";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE;
Blockly.Msg.VARIABLES_SET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;