// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.zh-hant');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "加入註解";
Blockly.Msg.AUTH = "Please authorize this app to enable your work to be saved and to allow it to be shared by you.";  // untranslated
Blockly.Msg.CHANGE_VALUE_TITLE = "修改值:";
Blockly.Msg.CHAT = "與您的合作者洽談藉由在此框輸入！";
Blockly.Msg.COLLAPSE_ALL = "收合積木";
Blockly.Msg.COLLAPSE_BLOCK = "收合積木";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "顏色 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "顏色 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";  // untranslated
Blockly.Msg.COLOUR_BLEND_RATIO = "比例";
Blockly.Msg.COLOUR_BLEND_TITLE = "混合";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "透過一個比率 (0.0-1.0)來混合兩種顏色。";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://en.wikipedia.org/wiki/Color";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "從調色板中選擇一種顏色。";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "隨機顏色";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "隨機選擇一種顏色。";
Blockly.Msg.COLOUR_RGB_BLUE = "藍";
Blockly.Msg.COLOUR_RGB_GREEN = "綠";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";  // untranslated
Blockly.Msg.COLOUR_RGB_RED = "紅";
Blockly.Msg.COLOUR_RGB_TITLE = "顏色";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "透過指定紅、綠、 藍色的值來建立一種顏色。所有的值必須介於 0 和 100 之間。";
Blockly.Msg.COMMENT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.COMMENT_TITLE = "Program Comment";  // untranslated
Blockly.Msg.COMMENT_TOOLTIP = "Comment Text";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://code.google.com/p/blockly/wiki/Loops#Loop_Termination_Blocks";  // untranslated
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "停止 迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "繼續下一個 迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "離開當前的 迴圈";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "跳過這個迴圈的其餘步驟，並繼續下一次的迴圈運算。";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "警告： 此積木僅可用於迴圈內。";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST = "自列表";
Blockly.Msg.CONTROLS_FOREACH_INPUT_INLIST_TAIL = "";
Blockly.Msg.CONTROLS_FOREACH_INPUT_ITEM = "取出每個";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "遍歷每個列表中的項目，將變量  '%1' 設定到該項目中，然後執行某些語句";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_FOR_INPUT_FROM_TO_BY = "從範圍 %1 到 %2 每隔 %3";
Blockly.Msg.CONTROLS_FOR_INPUT_WITH = "使用";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "從起始數到結尾數中取出變數 %1 的值，按指定的時間間隔，執行指定的積木。";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "將條件添加到'如果'積木。";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "加入一個最終，所有條件下都都執行的區塊到'如果'積木中";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "添加、 刪除或重新排列各區塊來此重新配置這個'如果'積木。";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "否則";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "否則如果";
Blockly.Msg.CONTROLS_IF_MSG_IF = "如果";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "當值為真時，執行一些語句";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "當值為真時，執行第一個語句，否則則執行第二個語句";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "如果第一個值為真，則執行第一個語句。否則當第二個值為真時，則執行第二個語句";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "如果第一個值為真，則執行第一個語句。否則當第二個值為真時，則執行第二個語句。如果前幾個敘述都不為真，則執行最後一個語句";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "執行";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "重複 %1 次";
Blockly.Msg.CONTROLS_REPEAT_TITLE_REPEAT = "重複";
Blockly.Msg.CONTROLS_REPEAT_TITLE_TIMES = "次數";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "多次執行一些語句";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "重複 直到";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "重複 當";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "當值為否時，執行一些語句";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "當值為真時，執行一些語句";
Blockly.Msg.DELETE_BLOCK = "刪除積木";
Blockly.Msg.DELETE_X_BLOCKS = "刪除 %1 塊積木";
Blockly.Msg.DISABLE_BLOCK = "停用積木";
Blockly.Msg.DUPLICATE_BLOCK = "複製";
Blockly.Msg.ENABLE_BLOCK = "啟用積木";
Blockly.Msg.EXPAND_ALL = "展開積木";
Blockly.Msg.EXPAND_BLOCK = "展開積木";
Blockly.Msg.EXPANSION_ELEVATION_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_ELEVATION_TOOLTI = "Gripper Servo Elevation";  // untranslated
Blockly.Msg.EXPANSION_EXP1OFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1OFF_TOOLTIP = "Turn Expansion 1 +3.3V Power Off";  // untranslated
Blockly.Msg.EXPANSION_EXP1ON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1ON_TOOLTIP = "Turn Expansion 1 +3.3V Power On";  // untranslated
Blockly.Msg.EXPANSION_EXP1_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP1_OFF = "expansion 1 power off";  // untranslated
Blockly.Msg.EXPANSION_EXP1_ON = "expansion 1 power on";  // untranslated
Blockly.Msg.EXPANSION_EXP1_TOOLTIP = "Expansion 1 Power Control";  // untranslated
Blockly.Msg.EXPANSION_EXP2OFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2OFF_TOOLTIP = "Turn Expansion 2 +3.3V Power Off";  // untranslated
Blockly.Msg.EXPANSION_EXP2ON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2ON_TOOLTIP = "Turn Expansion 2 +3.3V Power On";  // untranslated
Blockly.Msg.EXPANSION_EXP2_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_EXP2_OFF = "expansion 2 power off";  // untranslated
Blockly.Msg.EXPANSION_EXP2_ON = "expansion 2 power on";  // untranslated
Blockly.Msg.EXPANSION_EXP2_TOOLTIP = "Expansion 2 Power Control";  // untranslated
Blockly.Msg.EXPANSION_GRIPPER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_GRIPPER_TOOLTIP = "Gripper Servo Open/Close";  // untranslated
Blockly.Msg.EXPANSION_SERVOOFF_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVOOFF_TOOLTIP = "Turn Servo +5V Power Off";  // untranslated
Blockly.Msg.EXPANSION_SERVOON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVOON_TOOLTIP = "Turn Servo +5V Power On";  // untranslated
Blockly.Msg.EXPANSION_SERVO_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.EXPANSION_SERVO_OFF = "servo power off";  // untranslated
Blockly.Msg.EXPANSION_SERVO_ON = "servo power on";  // untranslated
Blockly.Msg.EXPANSION_SERVO_TOOLTIP = "Servo Power Control";  // untranslated
Blockly.Msg.EXTERNAL_INPUTS = "多行輸入";
Blockly.Msg.HELP = "說明";
Blockly.Msg.INLINE_INPUTS = "單行輸入";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://en.wikipedia.org/wiki/Linked_list#Empty_lists";  // untranslated
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "建立空列表";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "返回一個長度為 0 的列表，不包含任何資料記錄";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "加入";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "添加、 刪除或重新排列各區塊來此重新配置這個 列表 積木。";
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "使用這些值建立列表";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "將一個項目加入到列表中。";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "建立一個具備任意數量項目的列表。";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "第一筆";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "倒數第#筆";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "#";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_GET = "取值";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "取出並移除";
Blockly.Msg.LISTS_GET_INDEX_LAST = "最後一筆";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "隨機";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "移除";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "返回列表中的第一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_END = "返回在列表中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM_START = "返回在列表中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "返回列表中的最後一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "返回列表中隨機的一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "移除並返回列表中的第一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_END = "移除並返回列表中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM_START = "移除並返回列表中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "移除並返回列表中的最後一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "移除並返回列表中的隨機一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "移除列表中的第一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_END = "移除在列表中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM_START = "移除在列表中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "移除列表中的最後一個項目";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "移除列表中隨機的一個項目";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "到 倒數 # 位";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "到 #";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "到 最後";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#Getting_a_sublist";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "從 頭 取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "從倒數 # 取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "從 # 取得子列表";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "複製列表中指定的部分。";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "找出 第一個 項目出現";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#Getting_Items_from_a_List";  // untranslated
Blockly.Msg.LISTS_INDEX_OF_LAST = "找出 最後一個 項目出現";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "返回在列表中的第一個/最後一個匹配項目的索引值。如果未找到則返回 0。";
Blockly.Msg.LISTS_INLIST = "自列表";
Blockly.Msg.LISTS_IS_EMPTY_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#is_empty";  // untranslated
Blockly.Msg.LISTS_IS_EMPTY_TITLE = "%1 值為空";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#length_of";  // untranslated
Blockly.Msg.LISTS_LENGTH_TITLE = "長度 %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "返回列表的長度。";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#create_list_with";  // untranslated
Blockly.Msg.LISTS_REPEAT_TITLE = "建立列表使用項目 %1 重複 %2 次數";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "建立包含指定重複次數的 值 的列表。";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://code.google.com/p/blockly/wiki/Lists#in_list_..._set";  // untranslated
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "為";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "插入到";
Blockly.Msg.LISTS_SET_INDEX_SET = "設定";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "在列表的起始處添加一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_END = "插入在列表中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM_START = "插入在列表中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "在列表的尾端加入一個項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "在列表中隨機插入項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "設定列表中的第一個項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_END = "設定在列表中的指定位置的項目。#1 是最後一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM_START = "設定在列表中的指定位置的項目。#1 是第一個項目。";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "設定列表中的最後一個項目";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "設定列表中隨機的一個項目";
Blockly.Msg.LISTS_TOOLTIP = "如果該列表為空，則返回 真。";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "否";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "返回 真 或 否。";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "真";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "如果這兩個輸入區塊內容相等，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "如果第一個輸入大於第二個輸入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "如果第一個輸入大於或等於第二個輸入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "如果第一個輸入小於第二個輸入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "如果第一個輸入是小於或等於第二個輸入，返回 真。";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "如果這兩個輸入區塊內容不相等，返回 真。";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_NEGATE_TITLE = "非 %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "如果輸入的值是 否，則返回 真。如果輸入的值是 真 返回 否。";
Blockly.Msg.LOGIC_NULL = "空";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_NULL_TOOLTIP = "返回 空。";
Blockly.Msg.LOGIC_OPERATION_AND = "且";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_OPERATION_OR = "或";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "如果這兩個輸入值都為 真，則返回 真。";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "如果至少一個輸入的值為 真，返回 真。";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "測試";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "如果為非";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "如果為真";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "檢查 'test' 中的條件。如果條件為 真，將返回 '如果為 真' 值 ；否則，返回 '如果為 否' 的值。";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://en.wikipedia.org/wiki/Arithmetic";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "返回兩個數字的總和。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "返回兩個數字的商。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "返回兩個數字的差。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MODULO = "Return the remainder of the division operation.";  // untranslated
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "返回兩個數字的乘積。";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "返回第二個數字的指數的第一個數字。";
Blockly.Msg.MATH_BITWISE_AND = "&";  // untranslated
Blockly.Msg.MATH_BITWISE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_BITWISE_OR = "|";  // untranslated
Blockly.Msg.MATH_BITWISE_TOOLTIP = "Bitwise Operations";  // untranslated
Blockly.Msg.MATH_BITWISE_XOR = "^";  // untranslated
Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg.MATH_CHANGE_INPUT_BY = "自";
Blockly.Msg.MATH_CHANGE_TITLE_CHANGE = "修改";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "將數字添加到變量 '%1'。";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "返回一個的常見常量： π (3.141......)，e (2.718...)、 φ (1.618...)、 開方(2) (1.414......)、 開方(½) (0.707......) 或 ∞ （無窮大）。";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";  // untranslated
Blockly.Msg.MATH_CONSTRAIN_TITLE = "限制數字 %1 介於 (低) %2 到 (高) %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "限制數字介於兩個指定的數字之間";
Blockly.Msg.MATH_DIVISION_SYMBOL = "/";  // untranslated
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "可被整除";
Blockly.Msg.MATH_IS_EVEN = "是偶數";
Blockly.Msg.MATH_IS_NEGATIVE = "是負值";
Blockly.Msg.MATH_IS_ODD = "是奇數";
Blockly.Msg.MATH_IS_POSITIVE = "是正值";
Blockly.Msg.MATH_IS_PRIME = "是質數";
Blockly.Msg.MATH_IS_TOOLTIP = "如果數字是偶數，奇數，非負整數，正數、 負數或如果它是可被某數字整除，則返回 真 或 否。";
Blockly.Msg.MATH_IS_WHOLE = "是非負整數";
Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg.MATH_MODULO_SYMBOL = "%";  // untranslated
Blockly.Msg.MATH_MODULO_TITLE = "取餘數自 %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "回傳兩個數字相除的餘數";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "*";  // untranslated
Blockly.Msg.MATH_NUMBER_HELPURL = "https://en.wikipedia.org/wiki/Number";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "一個數字。";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "平均值 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "最大值 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "中位數 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "最小值 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "比較眾數 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "隨機抽取 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "標準差 自列表";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "總和 自列表";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "返回列表中數值的平均值 （算術平均值）。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "返回列表中的最大數字。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "返回列表中數值的中位數。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "返回列表中的最小數字。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "返回一個列表中的最常見項目的列表。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "從列表中返回一個隨機的項目。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "返回列表中數字的標準差。";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "返回列表中的所有數字的總和。";
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "取隨機分數";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "返回介於 （包含） 0.0 到 1.0 之間的隨機數。";
Blockly.Msg.MATH_RANDOM_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "取隨機整數介於 (低) %1 到 %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "回傳限制的數字區間內的隨機數字";
Blockly.Msg.MATH_RANDOM_TITLE = "Random Number (0-99)";  // untranslated
Blockly.Msg.MATH_RANDOM_TOOLTIP = "Return Random Number";  // untranslated
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "四捨五入";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "無條件捨去";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "無條件進位";
Blockly.Msg.MATH_ROUND_TOOLTIP = "將數字向上或向下舍入。";
Blockly.Msg.MATH_SHIFT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MATH_SHIFT_LEFT = "<<";  // untranslated
Blockly.Msg.MATH_SHIFT_RIGHT = ">>";  // untranslated
Blockly.Msg.MATH_SHIFT_TOOLTIP = "Bit Shift Operations";  // untranslated
Blockly.Msg.MATH_SINGLE_HELPURL = "https://en.wikipedia.org/wiki/Square_root";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "絕對值";
Blockly.Msg.MATH_SINGLE_OP_NEGATION = "negate";  // untranslated
Blockly.Msg.MATH_SINGLE_OP_ROOT = "開根號";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "返回指定數字的絕對值。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "返回指定數字指數的 e";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "返回指定數字的自然對數。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "返回指定數字的對數。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "返回指定數字的 negation。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "返回指定數字指數的10的冪次。";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "返回指定數字的平方根。";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";  // untranslated
Blockly.Msg.MATH_TRIG_ACOS = "acos";  // untranslated
Blockly.Msg.MATH_TRIG_ASIN = "asin";  // untranslated
Blockly.Msg.MATH_TRIG_ATAN = "atan";  // untranslated
Blockly.Msg.MATH_TRIG_COS = "cos";  // untranslated
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg.MATH_TRIG_SIN = "sin";  // untranslated
Blockly.Msg.MATH_TRIG_TAN = "tan";  // untranslated
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "返回指定角度的反餘弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "返回指定角度的反正弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "返回指定角度的反正切值。";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "返回指定角度的餘弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "返回指定角度的正弦值(非弧度）。";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "返回指定角度的正切值(非弧度）。";
Blockly.Msg.ME = "Me";  // untranslated
Blockly.Msg.MULTIMEDIA_DISPLAYBMP_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_DISPLAYBMP_TOOLTIP = "Display BMP File on OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_DOUPDATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_DOUPDATE_TOOLTIP = "Do an Update to the OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_HIGH = "volume high";  // untranslated
Blockly.Msg.MULTIMEDIA_LOW = "volume low";  // untranslated
Blockly.Msg.MULTIMEDIA_MEDIUM = "volume medium";  // untranslated
Blockly.Msg.MULTIMEDIA_MUTE = "volume mute";  // untranslated
Blockly.Msg.MULTIMEDIA_PLAYWAV_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_PLAYWAV_TOOLTIP = "Play WAV File on Jade Robot";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_TITLE = "playing active";  // untranslated
Blockly.Msg.MULTIMEDIA_POLLWAV_TOOLTIP = "Return Not Zero if WAV File still playing";  // untranslated
Blockly.Msg.MULTIMEDIA_STOPUPDATE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_STOPUPDATE_TOOLTIP = "Stop Updating the OLED";  // untranslated
Blockly.Msg.MULTIMEDIA_VOLUME_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.MULTIMEDIA_VOLUME_TOOLTIP = "Set Speaker Volume";  // untranslated
Blockly.Msg.NEW_VARIABLE = "新變量...";
Blockly.Msg.NEW_VARIABLE_TITLE = "新變量名稱:";
Blockly.Msg.OLED_COLOR_BLACK = "color black";  // untranslated
Blockly.Msg.OLED_COLOR_GREEN = "color green";  // untranslated
Blockly.Msg.OLED_COLOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.OLED_COLOR_TOOLTIP = "Set OLED Draw Color";  // untranslated
Blockly.Msg.OLED_DRAW_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.OLED_DRAW_LINE = "draw line";  // untranslated
Blockly.Msg.OLED_DRAW_RECT = "draw rectangle";  // untranslated
Blockly.Msg.OLED_DRAW_TOOLTIP = "Draw from Cursor to End";  // untranslated
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "allow statements";  // untranslated
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "與：";
Blockly.Msg.PROCEDURES_CALLNORETURN_CALL = "呼叫";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "執行使用者定義的函數 '%1'。";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "執行使用者定義的函數 '%1' 並使用它的回傳值";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "與：";
Blockly.Msg.PROCEDURES_CREATE_DO = "建立 '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "流程";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "到";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "創建一個無回傳值的函數。";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = "functionName";  // untranslated
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "回傳";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "創建一個有回傳值的函數。";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "警告: 此函數中有重複的參數。";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "高亮顯示函式定義";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "如果值為 真，則返回第二個值。";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "警告: 此積木僅可在定義函式時使用。";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "變量:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Add an input to the function.";  // untranslated
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "參數";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Add, remove, or reorder inputs to this function.";  // untranslated
Blockly.Msg.REMOVE_COMMENT = "移除註解";
Blockly.Msg.RENAME_VARIABLE = "重新命名變量...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "將所有 \"%1\" 變量重新命名為:";
Blockly.Msg.ROBOT_LED_FLASH = "led flash";  // untranslated
Blockly.Msg.ROBOT_LED_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.ROBOT_LED_OFF = "led off";  // untranslated
Blockly.Msg.ROBOT_LED_ON = "led on";  // untranslated
Blockly.Msg.ROBOT_LED_TOOLTIP = "Set LED";  // untranslated
Blockly.Msg.SENSOR_BATTERY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_BATTERY_TITLE = "battery level";  // untranslated
Blockly.Msg.SENSOR_BATTERY_TOOLTIP = "Return Battery Level";  // untranslated
Blockly.Msg.SENSOR_BUTTON_DOWN = "button down pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_ENTER = "button enter pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_BUTTON_LEFT = "button left pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_RIGHT = "button right pressed";  // untranslated
Blockly.Msg.SENSOR_BUTTON_TOOLTIP = "Return Button State";  // untranslated
Blockly.Msg.SENSOR_BUTTON_UP = "button up pressed";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_LEFT = "light left";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_REAR = "light rear";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_RIGHT = "light right";  // untranslated
Blockly.Msg.SENSOR_ROBOTLIGHT_TOOLTIP = "Returns Light Sensor.";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_LEFT = "line left";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_MIDDLE = "line middle";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_RIGHT = "line right";  // untranslated
Blockly.Msg.SENSOR_ROBOTLINE_TOOLTIP = "Returns Line Sensor.";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_LEFTFRONT = "object left front";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_LEFTSIDE = "object left side";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_REAR = "object rear";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_RIGHTFRONT = "object right front";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_RIGHTSIDE = "object right side";  // untranslated
Blockly.Msg.SENSOR_ROBOTOBJECT_TOOLTIP = "Returns Object Sensor.";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_BLUE = "spectrometer blue";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_GREEN = "spectrometer green";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_IR880 = "spectrometer 880nm";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_IR940 = "spectrometer 940nm";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_RED = "spectrometer red";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_TOOLTIP = "Return Spectrometer Reading";  // untranslated
Blockly.Msg.SENSOR_SPECTROMETER_YELLOW = "spectrometer yellow";  // untranslated
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "後加入文字";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_modification";  // untranslated
Blockly.Msg.TEXT_APPEND_TO = "在";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "將一些文字追加到變量 '%1'。";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Adjusting_text_case";  // untranslated
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "轉成 小寫";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "轉成 首字母大寫";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "轉成 大寫";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "使用不同的大小寫複製這段文字。";
Blockly.Msg.TEXT_CHARAT_FIRST = "取第一個字元";
Blockly.Msg.TEXT_CHARAT_FROM_END = "取得 倒數第 # 個字元";
Blockly.Msg.TEXT_CHARAT_FROM_START = "取得 字元 #";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Extracting_text";  // untranslated
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "的字元在字串";
Blockly.Msg.TEXT_CHARAT_LAST = "取最後一個字元";
Blockly.Msg.TEXT_CHARAT_RANDOM = "取隨機一個字元";
Blockly.Msg.TEXT_CHARAT_TAIL = "";
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "返回位於指定位置的字元。";
Blockly.Msg.TEXT_CLEARDISPLAY_TOOLTIP = "Clear OLED Display";  // untranslated
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "將一個項目加入到字串中。";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "加入";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "添加、 刪除或重新排列各區塊來此重新配置這個文字積木。";
Blockly.Msg.TEXT_DRAWNUMBER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_DRAWNUMBER_TOOLTIP = "Draw the specified number";  // untranslated
Blockly.Msg.TEXT_DRAWTEXT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_DRAWTEXT_TOOLTIP = "Draw the specified text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "到 倒數第 # 個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "到 字元 #";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "到 最後一個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Extracting_a_region_of_text";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "自字串";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "取得一段字串 自 第一個字元";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "取得一段字串自 #";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "取得一段字串自 #";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "返回指定的部分文字。";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Finding_text";  // untranslated
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "在字串";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "尋找 第一個 出現的字串";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "尋找 最後一個 出現的字串";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "返回在第二個字串中的第一個/最後一個匹配項目的索引值。如果未找到則返回 0。";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Checking_for_empty_text";  // untranslated
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 為空";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "如果提供的字串為空，則返回 真。";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_creation";  // untranslated
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "建立字串使用";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "通過串起任意數量的項目來建立一段文字。";
Blockly.Msg.TEXT_LEFTMOTOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_LEFTMOTOR_TITLE = "Set Left Motor %1";  // untranslated
Blockly.Msg.TEXT_LEFTMOTOR_TOOLTIP = "Specify the Value for the Left Motor.";  // untranslated
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Text_modification";  // untranslated
Blockly.Msg.TEXT_LENGTH_TITLE = "長度 %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "返回這串文字的字元數（含空格） 。";
Blockly.Msg.TEXT_MOTORSFORWARD_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSFORWARD_TITLE = "Move Robot Forward";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_TITLE = "Turn Left";  // untranslated
Blockly.Msg.TEXT_MOTORSLEFT_TOOLTIP = "Turn Robot Left";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_TITLE = "Robot Reverse";  // untranslated
Blockly.Msg.TEXT_MOTORSREVERSE_TOOLTIP = "Move Robot Backward";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_TITLE = "Turn Right";  // untranslated
Blockly.Msg.TEXT_MOTORSRIGHT_TOOLTIP = "Turn Robot Right";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_TITLE = "Stop Robot";  // untranslated
Blockly.Msg.TEXT_MOTORSSTOP_TOOLTIP = "Stop Robot";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_TITLE = "Robot Stutter";  // untranslated
Blockly.Msg.TEXT_MOTORSSTUTTER_TOOLTIP = "Robot Stutter";  // untranslated
Blockly.Msg.TEXT_OLEDCLEARDISPLAY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDCURSOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDCURSOR_TOOLTIP = "Set the Draw Position";  // untranslated
Blockly.Msg.TEXT_OLEDEND_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_OLEDEND_TOOLTIP = "Set the End Draw Position";  // untranslated
Blockly.Msg.TEXT_PRINT_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_PRINT_TITLE = "印出 %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "印出指定的文字、 數字或其他值。";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Getting_input_from_the_user";  // untranslated
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "輸入數字";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "輸入文字";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "輸入 數字 並顯示提示訊息";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "輸入 文字 並顯示提示訊息";
Blockly.Msg.TEXT_RIGHTMOTOR_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_RIGHTMOTOR_TOOLTIP = "Specify the Value for the Right Motor.";  // untranslated
Blockly.Msg.TEXT_ROBOTDELAY_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_ROBOTDELAY_TITLE = "Delay in ms %1";  // untranslated
Blockly.Msg.TEXT_SETMOTORS_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.TEXT_SETMOTORS_TOOLTIP = "Specify the Value for the Motors.";  // untranslated
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "字元、 單詞或一行文字。";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://code.google.com/p/blockly/wiki/Text#Trimming_%28removing%29_spaces";  // untranslated
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "消除兩側空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "消除左側空格";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "消除右側空格";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "複製這段文字的同時刪除兩端多餘的空格。";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "變量";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "創立 '設定 %1'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.VARIABLES_GET_TAIL = "";
Blockly.Msg.VARIABLES_GET_TITLE = "";
Blockly.Msg.VARIABLES_GET_TOOLTIP = "返回此變量的值。";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "建立 '取得 %1'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://www.mimetics.ca/docs/Scratch%20Programming%20Outline%20-%202014.12.30.pdf";  // untranslated
Blockly.Msg.VARIABLES_SET_TAIL = "到";
Blockly.Msg.VARIABLES_SET_TITLE = "賦值";
Blockly.Msg.VARIABLES_SET_TOOLTIP = "設定此變量，好和輸入值相等。";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE;
Blockly.Msg.VARIABLES_SET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.VARIABLES_GET_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_CALLRETURN_CALL = Blockly.Msg.PROCEDURES_CALLNORETURN_CALL;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
